[WIP] feat: new dropdown
chatwoot/chatwoot pull request #10358
Opened 2024-10-28 11:13 UTC by scmmishra

# Pull Request Template

## Description

Please include a summary of the change and issue(s) fixed. Also, mention relevant motivation, context, and any dependencies that this change requires.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-11 09:35 UTC, scmmishra commented
@iamsivin @pranavrajs need review on this

2024-11-14 04:32 UTC, pranavrajs commented
@scmmishra Please take a look at this feedback. https://www.loom.com/share/2365090c4bcf4156beb79036ba01edf2. 

	1.	The feedback for the click action is somewhat slow.
	2.	The spacing between items doesn’t align with the gap between the actual sidebar items.

2024-11-14 04:33 UTC, pranavrajs commented on app/javascript/dashboard/components-next/sidebar/SidebarProfileMenuStatus.vue
> +// import DropdownSeparator from 'next/dropdown-menu/base/DropdownSeparator.vue';
👃

2024-11-14 04:34 UTC, pranavrajs requested changes
Some minor feedback. Otherwise looks fine.

2024-11-18 08:10 UTC, scmmishra commented
Hey @pranavrajs made the following changes in line with the feedback

1. Reduced the spacing around the dropdown items, made some layout tweaks with @absurdiya 
2. Updated the import across the dropdown component
3. We didn't have optimistic updates for the status changes previously, but it was straightforward to add, so made the changes for it. Let me know if you have any feedback about it :)

PTAL and let me know if this needs any changes. Thx.

<details><summary>P.S. Previous case (without optimistic updates)</summary>
<p>

Video from app.chatwoot.com with network throttling 

https://github.com/user-attachments/assets/b4f61872-3e2c-4c1b-88f0-8fe84e24773a

</p>
</details>

2024-11-19 01:29 UTC, merged