Lable title shows text error
chatwoot/chatwoot pull request #1299
Opened 2020-10-02 21:25 UTC by m4tr1k

# Pull Request Template

## Description

@sojan-official wanted to put error messages on label titles to notify the user what caused the following error (which is blank spaces). As soon as the label has space, the app notifies the user with an error message.

Fixes #1298 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I locally tested this on my machine and it is showing the error message as soon as the label has space.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-10-04 17:29 UTC, pranavrajs commented on app/javascript/dashboard/assets/scss/widgets/_forms.scss
> +  color: darken(get-color(alert), 25%);
Please use color variables from `dashboard/assets/scss/variables.scss` or `shareda/assets/stylesheets/colors.scss`

2020-10-04 17:29 UTC, pranavrajs commented on app/javascript/dashboard/assets/scss/widgets/_forms.scss
> +  margin-bottom: 1.6rem !important;
Please use the space variable. `(dashboard/assets/scss/variables.scss)`

2020-10-04 17:30 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/settings/labels/AddLabel.vue
> +          :errorText="'Only Alphabets, Numbers, Hyphen and Underscore are allowed!'"
Please move this i18n file.

2020-10-04 17:30 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/settings/labels/validations.js
> +export const validLabelCharacters = (str = '') => !str.includes(' ');
Can we regex here instead of this?

2020-10-04 17:31 UTC, pranavrajs requested changes
@m4tr1k Thanks for the PR. I've some comments about the PR. Please take a look and let me know your thoughts.

2020-10-04 17:33 UTC, m4tr1k commented
@pranavrajs of course, thanks for pointing those details. Gonna work on them soon and then you can review again 😄

2020-10-04 18:54 UTC, m4tr1k commented
@pranavrajs let me know if there's anything to fix

2020-10-05 17:25 UTC, pranavrajs commented
@m4tr1k Thanks for the fixes. I will test it out and see the behaviour and will let you know.

2020-11-24 14:08 UTC, nithindavid requested changes

2020-11-24 14:08 UTC, nithindavid commented on app/javascript/dashboard/assets/scss/widgets/_forms.scss
> +  margin-bottom: $space-normal !important;
Is important mandatory here ?

2020-11-24 14:08 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/settings/labels/validations.js
> +export const validLabelCharacters = (str = '') => !/ /.test(str);
👍

2021-03-03 12:36 UTC, sojan-official commented
Closing this PR since it hasn't been active for a while.

2021-03-03 12:36 UTC, closed without merging