feature: IP lookup
chatwoot/chatwoot pull request #1315
Opened 2020-10-05 15:16 UTC by sojan-official

# Pull Request Template

## Description

- feature to store contact IP for accounts
- IP lookup through geocoder gem

Fixes #1122 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-10-19 19:06 UTC, pranavrajs commented on db/schema.rb
> +
Please remove bot flow schema changes

2020-10-19 19:06 UTC, pranavrajs requested changes
Please remove the bot flow changes from schema.rb

2020-10-27 20:44 UTC, merged

2020-12-15 19:35 UTC, ReactRaja commented
Was this ever added?

2020-12-15 19:41 UTC, sojan-official commented
@ReactRaja  you can find the docs to enable this on https://www.chatwoot.com/docs/self-hosted/enable-ip-logging

2020-12-15 21:34 UTC, ReactRaja commented
Well geo2ip is paid thing hmm. 
Would geolite2 work?

2020-12-20 21:41 UTC, ReactRaja commented
> 
> 
> Well geo2ip is paid thing hmm.
> Would geolite2 work?

So?

2020-12-21 07:38 UTC, sojan-official commented
@ReactRaja chatwoot uses the locally downloaded MaxmindDB. It should be free to use.

2020-12-21 17:28 UTC, ReactRaja commented
Using  `account = Account.find(account_id)` after `account_id = maxmindUSERID` seems to give an error

`ActiveRecord::RecordNotFound (Could'nt find Account with 'id'=maxmindUSERID)` 

Any idea what might be causing this?

2020-12-21 17:33 UTC, sojan-official commented
@ReactRaja  account_id is your chatwoot account id. not your maxmind user id

2020-12-22 16:20 UTC, ReactRaja commented
Huh so to enable for all my agents i would have to manually select their account id and enable it for them one by one? Seems a bit redundant if thats the case

2020-12-22 18:45 UTC, sojan-official commented
@ReactRaja  account id is different from your user id.  when you load your dashboard the URL should be like this.

https://app.chatwoot.com/app/accounts/1/dashboard

1 -> is your account id

2021-12-18 00:30 UTC, nh2 commented
@sojan-official Could it be documented whether IP logging is available/configurable on the hosted https://app.chatwoot.com?

The docs seem to talk about the self-hosted version only.