Dev/chinese translation
chatwoot/chatwoot pull request #1446
Opened 2020-11-24 07:23 UTC by Amhwang

## Description

1. finish chinese translation and load as zh_CN;
2. fix permission for docker/entrypoints/rails.sh;
3. add  POSTGRES_PORT=5432 to .env example because if not config this arg,and error will be thrown by pg_isready;

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

build it as an image and test it after deployed to kubernetes

## Checklist:

- [ √] My code follows the style guidelines of this project
- [√ ] I have performed a self-review of my own code
- [√ ] I have commented on my code, particularly in hard-to-understand areas
- [ √] I have made corresponding changes to the documentation
- [ √] My changes generate no new warnings
- [ √] I have added tests that prove my fix is effective or that my feature works
- [ √] New and existing unit tests pass locally with my changes
- [ √] Any dependent changes have been merged and published in downstream modules

2020-11-26 06:33 UTC, pranavrajs commented on db/seeds.rb
> -SuperAdmin.create!(email: 'john@acme.inc', password: '123456') unless Rails.env.production?
Hey @hwangww Why is this deleted?

2020-11-26 06:33 UTC, pranavrajs commented on config/secrets.yml
> +  secret_key_base: 3beeee45bc938475ecba45075c53aae0f94299a83f824b25bbaf7965b4b0c60ff2b0c66c9047a026578deb5ecadabaa602891be2be66ed123a7b26876d4daddf
Hey @hwangww, why is this changed?

2020-11-26 06:33 UTC, pranavrajs commented on app/javascript/widget/components/template/EmailInput.vue
> +const phone = regex('phone', /^[1][3,4,5,6,7,8,9][0-9]{9}$/);
I don't understand the change here.

2020-11-26 06:35 UTC, pranavrajs requested changes
@hwangww Thanks for the PR, part of the changes seems good. There are a lot of unnecessary changes. Can you please remove those? I would also recommend using https://translate.chatwoot.com for translation changes.

Please see this guide. https://github.com/chatwoot/chatwoot/blob/develop/docs/contributing/translating-chatwoot-to-your-language.md

2020-11-30 01:22 UTC, hwangww commented on db/seeds.rb
> -SuperAdmin.create!(email: 'john@acme.inc', password: '123456') unless Rails.env.production?
I'll check it.

2021-03-03 12:06 UTC, sojan-official commented
@hwangww  I tried working on this PR, but there is a lot of conflicts with the upstream. I couldn't do much about them because they are translation conflicts.  Let's reopen this PR if you decide to work on this again. 

for future it will be easier if we could do translations via https://translate.chatwoot.com

2021-03-03 12:06 UTC, closed without merging