chore: add count and current page in notification meta details
chatwoot/chatwoot pull request #1619
Opened 2021-01-06 15:18 UTC by muhsin-k

Fixes #1616

2021-01-06 16:09 UTC, pranavrajs commented on db/schema.rb
> -    t.index ["taggable_type", "taggable_id"], name: "index_taggings_on_taggable_type_and_taggable_id"
Please revert this changes.

2021-01-06 16:09 UTC, pranavrajs commented on db/schema.rb
> -    t.uuid "uuid", default: -> { "gen_random_uuid()" }, null: false
Please revert this change.

2021-01-06 16:11 UTC, pranavrajs requested changes

2021-01-06 16:11 UTC, pranavrajs commented on app/controllers/api/v1/accounts/notifications_controller.rb
>      @notifications = current_user.notifications.where(account_id: current_account.id).page params[:page]
Please create a method and memoize `current_user.notifications.where(account_id: current_account.id)`

2021-01-06 16:11 UTC, pranavrajs commented on app/controllers/api/v1/accounts/notifications_controller.rb
>      @notifications = current_user.notifications.where(account_id: current_account.id).page params[:page]
use @current_page instead of params[:page]

2021-01-12 15:46 UTC, muhsin-k commented
@pranavrajs Please check the latest changes

2021-01-13 11:34 UTC, pranavrajs approved these changes

2021-01-13 11:34 UTC, merged