feat: installation config in super admin console
chatwoot/chatwoot pull request #1641
Opened 2021-01-12 07:48 UTC by sony-mathew

## Description

* Added the ability for super admins to view, edit and update installation config values. Also, they can add new installation config values. The impact of editing and adding depends on which all installation config values are being used in the code.
* Known limitation now: Ability to edit hash values (for eg: feature flags) are disabled. This requires more work and will be taken up in a secondary set of changes.
* Minor UX improvement. Clicking on the Sidekiq option in the super admin sidebar will now open the Sidekiq dashboard in a new tab rather than in the same tab that you were using super admin.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested in a local development environment.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-01-12 13:27 UTC, pranavrajs commented
<img width="1434" alt="Screenshot 2021-01-12 at 6 57 49 PM" src="https://user-images.githubusercontent.com/2246121/104320226-12e48e80-5508-11eb-9237-70410598222e.png">

2021-01-12 13:28 UTC, pranavrajs requested changes
Please pull the existing database and see something breaks, I couldn't view the page because of the screenshot attached.

2021-01-12 15:04 UTC, sony-mathew commented
> Please pull the existing database and see something breaks, I couldn't view the page because of the screenshot attached.

It's fixed now @pranavrajs . Thanks for reviewing.

2021-01-12 17:33 UTC, sojan-official commented
We should have a filter for the installation configs that are exposed in the UI. So we can hide the configs that shouldn't be tampered with.

2021-01-12 17:47 UTC, sony-mathew commented
@sojan-official I agree with that. Can we take that up in the next set of changes? Or do you think it is better to do it in this PR itself?

2021-01-13 06:07 UTC, sony-mathew commented
@pranavrajs @sojan-official I have incorporated the above-mentioned changes. Let me know if any changes need to be done on top of this.

2021-01-13 11:03 UTC, pranavrajs commented
@sony-mathew I cannot create a new installation config. https://www.loom.com/share/a8ebc9f990d14dc6a0eda720aa3daa80

2021-01-13 16:42 UTC, sony-mathew commented
@pranavrajs Fixed the issue.

2021-01-15 07:51 UTC, pranavrajs approved these changes

2021-01-15 07:51 UTC, merged

2021-01-26 19:42 UTC, orlando commented
I think this broke the bootstrap using docker. I get this error when running migrations.


```ruby
undefined local variable or method `locked' for #<InstallationConfig:0x00007fdaf1615368>
Did you mean?  lock!
/gems/ruby/2.7.0/gems/activemodel-6.0.3.4/lib/active_model/attribute_methods.rb:432:in `method_missing'
/app/app/models/installation_config.rb:39:in `set_lock'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:604:in `catch'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:604:in `block in default_terminator'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:201:in `block in halting'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `each'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `invoke_before'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:134:in `run_callbacks'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
/gems/ruby/2.7.0/gems/activemodel-6.0.3.4/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/gems/ruby/2.7.0/gems/activemodel-6.0.3.4/lib/active_model/validations.rb:337:in `valid?'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:68:in `valid?'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:84:in `perform_validations'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:47:in `save'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:314:in `block in save'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:212:in `transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:314:in `save'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/suppressor.rb:44:in `save'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:38:in `create'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:100:in `block in create'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:407:in `block in scoping'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:784:in `_scoping'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:407:in `scoping'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:100:in `create'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:169:in `find_or_create_by'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/querying.rb:21:in `find_or_create_by'
/app/lib/config_loader.rb:62:in `save_as_new_config'
```