Chore: Sets up store for teams settings page
chatwoot/chatwoot pull request #1727
Opened 2021-02-03 08:59 UTC by nithindavid

Fixes part of #866

2021-02-03 15:39 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/specs/teamMembers/getters.spec.js
> +        1: teamMembers[0],
This is supposed to be an array right.

```js
{
  1: [{ ...agent1 }, { ..agent2 }]
}
```

2021-02-03 15:41 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/specs/teamMembers/getters.spec.js
> +        isUpdatingAutoAssignment: false,
Please remove irrelevant flags.

2021-02-03 15:42 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/specs/teams/getters.spec.js
> +        isDeleting: false,
Please remove unnecessary flags.

2021-02-03 15:43 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/teams/mutations.js
> +    const { [teamId]: toDelete, ...records } = $state.records;
Where is `toDelete` defined?

2021-02-03 15:44 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/specs/teams/mutations.spec.js
> +    it('delete label record', () => {
label?

2021-02-03 15:44 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/specs/teams/mutations.spec.js
> +    it('update label record', () => {
label?

2021-02-03 15:44 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/specs/teams/mutations.spec.js
> +    it('push newly created label to the store', () => {
label?

2021-02-03 15:44 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/specs/teams/mutations.spec.js
> +    it('set label records', () => {
label?

2021-02-03 15:46 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/specs/teams/getters.spec.js
> +    });
please remove unnecessary lines.

2021-02-03 15:46 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/teams/actions.js
> +      return team;
Why is a return required here?

2021-02-03 15:47 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/teams/getters.js
> +    return Object.values($state.records);
Would this maintain order? Should we sort based on team id.

2021-02-03 15:47 UTC, pranavrajs requested changes
Please fix the comments.

2021-02-03 15:55 UTC, nithindavid commented on app/javascript/dashboard/store/modules/teams/mutations.js
> +    const { [teamId]: toDelete, ...records } = $state.records;
Es6 syntax

2021-02-03 15:56 UTC, nithindavid commented on app/javascript/dashboard/store/modules/teams/actions.js
> +      return team;
To avoid watch in vue

2021-02-03 16:09 UTC, nithindavid commented
@pranavrajs Fixed errors

2021-02-04 07:49 UTC, pranavrajs approved these changes

2021-02-04 07:50 UTC, merged