Enhancement: Redesigned search UI
chatwoot/chatwoot pull request #1845
Opened 2021-03-02 05:15 UTC by sivin-git

Redesigned the search UI to match the overall look and feel.

**After**

https://user-images.githubusercontent.com/64252451/109600822-cac70d00-7b43-11eb-88d2-cd2d907f0e9c.mov

**Before**
<img width="1239" alt="Screenshot 2021-03-02 at 10 38 49 AM" src="https://user-images.githubusercontent.com/64252451/109600677-7c197300-7b43-11eb-8143-e90e294f9e9a.png">

**Todo**

1.  Search highlight.
2. Add Click result for conversation result.

2021-03-04 09:41 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
> +  <div class="search-header">
```suggestion
  <div class="search-wrap">
```

2021-03-05 08:20 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
> +  props: {},
Remove this line

2021-03-05 08:22 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
> +            v-if="searchTerm && conversations.length && !uiFlags.isFetching"
Move this condition inside `v-if` as a new computed function

2021-03-05 08:22 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
> +              searchTerm && !conversations.length && !uiFlags.isFetching
Reuse the above computed function created in previous comment

2021-03-14 08:19 UTC, nithindavid submitted a review, later dismissed

2021-03-14 14:08 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/conversation/search/PopOverSearch.vue
> +              <span v-if="resultsCount !== 0" class="message-counter">
`!resultsCount` is enough

2021-03-14 14:08 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/conversation/search/SearchMessageItem.vue
> +  align-items: last baseline;
last?

2021-03-14 14:09 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/conversationSearch.js
> +
Unnecessary line.

2021-03-14 14:11 UTC, pranavrajs requested changes
Nice work on breaking the search component into smaller components. I have some minor comments, please see the individual review comments.

2021-03-15 13:08 UTC, merged