File upload size check in widget and dashboard
chatwoot/chatwoot pull request #1975
Opened 2021-03-23 08:23 UTC by muhsin-k

Fixes #1974 
**Preview**
![Screenshot 2021-03-23 at 1 51 37 PM](https://user-images.githubusercontent.com/12408980/112115420-68779000-8b76-11eb-9161-86984ed67583.png)

2021-04-02 08:02 UTC, pranavrajs requested changes
Nice work! 🎉

Overall the changes look nice. Please fix the individual comments on the PR.

2021-04-02 08:02 UTC, pranavrajs commented on app/javascript/widget/views/Home.vue
> +    bus.$on('on-attachment-error', () => {
I would suggest keeping this name as a constant in a separate file if possible so that we know about all the events we are emitting in one place.

2021-04-02 08:02 UTC, pranavrajs commented on app/javascript/widget/views/Home.vue
> +    padding: $space-slab;
Can't we use the CSS variable here?

2021-04-05 09:51 UTC, muhsin-k commented
@pranavrajs Please check the latest changes

2021-04-05 09:55 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
> +        if (checkFileSizeLimit(file, MAXIMUM_FILE_UPLOAD_SIZE)) {
Please combine this with the previous line.

2021-04-05 09:56 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
> +          if (!file) {
This check is not required if you are checking the existence of the file at the beginning of the function.

2021-04-05 13:13 UTC, muhsin-k commented
@pranavrajs Changes are updated as per code review

2021-04-12 05:12 UTC, pranavrajs approved these changes
Looks good! @nithindavid / @sojan-official Can you please do a QA here?

@muhsin-k Could you please write down the steps for QA?

2021-04-12 05:54 UTC, muhsin-k commented
@nithindavid / @sojan-official 

**Widget**
- Try uploading a file with a size of more than 40MB
- Expected result - Shows a banner message "File exceeds the 40MB attachment limit"

**Dashboard**
- Try uploading a file with a size of more than 40MB 
- Expected result-Shows a toast alert "File exceeds the 40MB attachment limit"

2021-04-15 16:58 UTC, merged