enhancement: Show agent availability status in conversation assignees select list
chatwoot/chatwoot pull request #2122
Opened 2021-04-19 06:01 UTC by muhsin-k

Fixes #1892

2021-04-19 13:15 UTC, nithindavid approved these changes

2021-04-19 13:19 UTC, nithindavid commented
@muhsin-k Does this cover the Agent dropdown on sidebar ?

2021-04-19 15:21 UTC, muhsin-k commented
> @muhsin-k Does this cover the Agent dropdown on sidebar ?

Yes. Created a new component **AvailabilityStatusBadge** and used it everywhere.

2021-04-19 16:43 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/ConversationHeader.vue
> +.status-badge {
Can you remove this ?

2021-04-19 16:43 UTC, nithindavid requested changes

2021-04-19 16:43 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
> +.status-badge {
This one also

2021-04-19 16:45 UTC, nithindavid requested changes
Please see comments

2021-04-19 17:23 UTC, muhsin-k commented
@nithindavid Please check the lastest changes

2021-04-21 06:36 UTC, nithindavid approved these changes

2021-04-21 06:48 UTC, merged