Feat: Creates note component for CRM
chatwoot/chatwoot pull request #2181
Opened 2021-04-29 12:33 UTC by iamsivin

<img width="1674" alt="Screenshot 2021-04-29 at 6 02 11 PM" src="https://user-images.githubusercontent.com/64252451/116550991-0b10f480-a915-11eb-99a4-e4726cdce020.png">

2021-04-29 18:45 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.vue
> +    .button--emoji {
We might need to add small icon button to WootButton

2021-04-29 18:47 UTC, nithindavid approved these changes
Looks good. Will merge once storybook PR is merged.
Also if possible add small icon button styles to WootButton in a new PR.

2021-04-30 05:17 UTC, nithindavid requested changes

2021-04-30 05:17 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ContactNote.vue
> +          class="button clear ion-trash-b button--emoji"
Can we use appropriate  props for woot-button?

2021-04-30 06:30 UTC, nithindavid approved these changes

2021-04-30 06:32 UTC, merged

2021-04-30 06:59 UTC, muhsin-k commented
@iamsivin Good work 👏🏻. I have a small suggestion here if you can make the story file name in the format of `[component_name].stories.js`. It will be easy and helpful to find the stories easily

2021-04-30 09:57 UTC, iamsivin commented
> @iamsivin Good work 👏🏻. I have a small suggestion here if you can make the story file name in the format of `[component_name].stories.js`. It will be easy and helpful to find the stories easily

Yeah sure.