feat: Campaign widget
chatwoot/chatwoot pull request #2227
Opened 2021-05-05 18:26 UTC by muhsin-k

- Fetch campaigns 
- Store campaigns
- Timer for executing campaigns
- API call to events endpoint

2021-05-06 13:44 UTC, nithindavid requested changes
Please see the comments.

2021-05-06 13:44 UTC, nithindavid commented on app/javascript/widget/App.vue
> +      if (enabledLanguages.some((lang) => lang.iso_639_1_code === locale)) {
There are some syntax changes with parenthesis of arrow functions, which is not aligned to other parts of code. Can you revert them ?

2021-05-06 13:44 UTC, nithindavid commented on app/javascript/widget/api/campaign.js
> +      params: {
We can move this inside the endPoints function.

2021-05-06 13:44 UTC, nithindavid commented on app/javascript/widget/helpers/campaignTimer.js
> +export default { start };
Can we omit the default export for helpers ? so `import { start } from 'widget/helpers/campaignTimer';` would work.

2021-05-07 07:18 UTC, pranavrajs commented
@muhsin-k Would you please share the test cases and assign the PR to someone for testing it?

2021-05-07 13:01 UTC, nithindavid submitted a review, later dismissed

2021-05-10 07:22 UTC, sojan-official approved these changes

2021-05-10 07:31 UTC, merged