feat: Edit campaigns
chatwoot/chatwoot pull request #2230
Opened 2021-05-06 05:49 UTC by muhsin-k

- Added the ability to update campaigns

2021-05-06 07:32 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
> +            />
Can we show validation errors here and for forms below?

2021-05-06 07:33 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
> +            <woot-submit-button
`woot-button`

2021-05-06 07:33 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
> +            <button class="button clear" @click.prevent="onClose">
`woot-button`

2021-05-06 07:35 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
> +      this.timeOnPage = this.selectedCampaign.trigger_rules.time_on_page;
Can we destruct the object into constants to avoid the snake case usage.

2021-05-06 07:43 UTC, nithindavid requested changes
Please see the comments. Also there are some errors on console, please fix them too.

2021-05-06 13:35 UTC, nithindavid requested changes
Please see the comment added.

2021-05-06 13:35 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
> +          <div class="medium-12 columns button-wrapper">
If we could just keep `modal-footer` there by removing other classes, The buttons would align as intended .

2021-05-06 13:59 UTC, muhsin-k commented
@nithindavid Requested changes are done.

2021-05-07 05:38 UTC, nithindavid reviewed
Have left a minor comment. Please see it.

2021-05-07 05:38 UTC, nithindavid commented on app/javascript/dashboard/store/modules/campaigns.js
> +  update: async function updateCampaign({ commit }, { id, ...updateObj }) {
Can we change it like below to avoid multiple names for same function?
`async update(...) {`

2021-05-07 07:19 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/settings/inbox/Settings.vue
> +          },
Let us remove this and add this as a separate PR once the widget side is merged.

2021-05-07 13:02 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/settings/inbox/components/EditCampaign.vue
> +.button-wrapper {
This style is not used I think, please remove this.

2021-05-07 14:46 UTC, sojan-official approved these changes
LGTM in testing

2021-05-10 07:10 UTC, nithindavid approved these changes

2021-05-10 07:10 UTC, merged