feat: new label dropdown using dropdown component
chatwoot/chatwoot pull request #2243
Opened 2021-05-10 05:42 UTC by iamsivin

2021-05-10 07:02 UTC, nithindavid requested changes

2021-05-10 07:02 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/conversation/labels/LabelBox.vue
> +      this.selectedLabels.filter(label => label.title === value.title);
`this.selectedLabels.filter(label => label.title === value.title);` will return a new array without `value.title`. Assign the result this to a new `const` and assign it to  `this.selectedLabels`. Then call `this.onUpdateLabels(this.selectedLabels);`

2021-05-11 07:13 UTC, iamsivin commented on app/javascript/shared/components/ui/dropdown/AddLabel.vue
> +  padding: var(--space-micro) var(--space-small);
To be removed button component tiny button styles are fixed.

2021-05-11 07:14 UTC, iamsivin commented on app/javascript/shared/components/ui/dropdown/AddLabel.vue
> +  padding: var(--space-micro) var(--space-small);
To be removed when button component tiny button styles are fixed.

2021-05-11 17:32 UTC, nithindavid commented
@iamsivin Please move the conversations block to the end of list as Pranav mentioned.

2021-05-11 17:32 UTC, nithindavid requested changes
👆

2021-05-13 06:27 UTC, nithindavid requested changes

2021-05-13 06:27 UTC, nithindavid commented on app/javascript/shared/components/ui/dropdown/AddLabel.vue
> +  line-height: 1.4rem;
Use variable here.

2021-05-13 16:25 UTC, nithindavid approved these changes

2021-05-17 05:20 UTC, pranavrajs commented
@nithindavid I have tested this out on staging. Can we merge it? Is there something left to be done on this PR?

2021-05-17 06:30 UTC, merged