Feat: Creates reminder list component for CRM
chatwoot/chatwoot pull request #2258
Opened 2021-05-12 16:44 UTC by iamsivin

https://user-images.githubusercontent.com/64252451/118013051-555f9000-b36f-11eb-9f53-ece63cba4ea0.mov

2021-05-13 06:06 UTC, nithindavid requested changes

2021-05-13 06:06 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderList.vue
> +    },
@iamsivin Add a boolean prop `isCompleted` to set the state of checkbox.

2021-05-13 06:06 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderList.vue
> +.note-wrap:hover {
Can we avoid this class `note` class names here ?

2021-05-13 06:06 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderList.vue
> +<template>
Can we rename this component to `ReminderItem`?

2021-05-14 07:09 UTC, nithindavid requested changes

2021-05-14 07:09 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +  <div class="item-wrap">
Use `reminder-wrap`

One suggestion here while naming classes. https://css-tricks.com/bem-101/

2021-05-14 07:09 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +    <div class="radio-button">
Classname to `status-wrap`

2021-05-14 07:09 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +      <div class="text">
class name to `content`

2021-05-14 07:09 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +            <div class="label-text">
Use `woot-label` component

2021-05-14 07:09 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +  methods: {
Need to emit an event when user clicks radio button to mark a task as completed.

2021-05-14 07:09 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +            <i class="icon ion-android-calendar" />
Use woot label with icon

2021-05-19 08:20 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +      type: Number,
The type of date is`String`.

2021-05-19 08:20 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +      <input :checked="isCompleted" @click="onClick" type="radio" />
Attribute "type" should go before "@click".

2021-05-19 08:21 UTC, muhsin-k commented
@iamsivin Nice work. Please the inline comments

2021-05-24 16:57 UTC, nithindavid requested changes

2021-05-24 16:57 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +      <div class="content">
use `p` tag here.

2021-05-24 16:57 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +            bg-color="#f4f6fb"
We are already using `color-scheme` prop so this `bg-color` is not needed.

2021-05-24 16:57 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +            bg-color="#f4f6fb"
remove bg-color

2021-05-24 16:57 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +            class="button-wrap"
Can we use more contextual class names? `action-button`?

2021-05-28 16:58 UTC, nithindavid requested changes

2021-05-28 16:58 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +      color: var(--color-body);
Can be removed since `p` comes default with this color.

2021-05-28 16:58 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ReminderItem.vue
> +    .action-button {
Can we move this inside line `117`

2021-06-02 17:11 UTC, nithindavid approved these changes

2021-06-02 17:18 UTC, merged