feat: Creates add reminder component for CRM
chatwoot/chatwoot pull request #2264
Opened 2021-05-14 07:10 UTC by iamsivin

https://user-images.githubusercontent.com/64252451/118234713-5dbfe400-b4b1-11eb-982c-19d1fc093fe9.mov

2021-05-14 14:49 UTC, aherrera31 commented
@iamsivin - can we assign reminders to colleagues, and have them view all of their reminders in 1 place?

2021-05-18 05:46 UTC, nithindavid commented
Thanks @aherrera31, It's a good feedback. We will iterate reminders and will add this option once the basic version is ready.

2021-05-18 05:49 UTC, nithindavid requested changes

2021-05-18 05:49 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/AddReminder.vue
> +          class="input--note"
Can we remove usages for `note` and replace with `reminder`?

2021-05-19 12:38 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/AddReminder.vue
> +  <div class="text-wrap">
Can we rename to `wrap` just wrap?

2021-05-24 17:00 UTC, nithindavid requested changes

2021-05-24 17:00 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/AddReminder.vue
> +            <option value="" disabled selected>
Use a prop to get options, and do v-for to generate the options.

2021-05-26 10:30 UTC, nithindavid approved these changes

2021-05-26 10:30 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/AddReminder.vue
> +          <select class="label" @change="optionSelected($event)">
The naming `label` is misleading. Can we use task related name here `task__type` for this and below class names?

2021-05-26 10:30 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/AddReminder.vue
> +              :value="option.name"
use `option.id`

2021-05-26 10:30 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/AddReminder.vue
> +    <div
use button here instead of div.

2021-05-26 10:30 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/AddReminder.vue
> +    .input {
Use the default input styles.

2021-05-26 10:30 UTC, nithindavid requested changes
Please see the comments.

2021-05-28 17:00 UTC, nithindavid requested changes

2021-05-28 17:00 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/AddReminder.vue
> +          <div class="date-wrap">
Can we use this? https://get.foundation/sites/docs/forms.html#inline-labels-and-buttons

2021-06-02 17:18 UTC, nithindavid approved these changes

2021-06-02 17:23 UTC, merged