feat: Creates event timeline card component for CRM
chatwoot/chatwoot pull request #2291
Opened 2021-05-18 05:35 UTC by iamsivin

<img width="829" alt="Screenshot 2021-05-18 at 11 00 03 AM" src="https://user-images.githubusercontent.com/64252451/118595429-af75b080-b7c8-11eb-9401-1cfc3b5999fe.png">

2021-05-18 05:41 UTC, nithindavid requested changes

2021-05-18 05:41 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/TimelineCard.vue
> +    width: 3.6rem;
Please use `spacing` variable

2021-05-26 10:33 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/TimelineCard.vue
> +          <span class="event-type">{{ eventType }}</span>
Use h6 with `text-block-title`

2021-05-26 12:11 UTC, XuanThuLe commented on app/javascript/dashboard/routes/dashboard/contacts/components/TimelineCard.vue
> +          <span class="event-type">{{ eventType }}</span>
Ok

2021-06-02 17:23 UTC, nithindavid approved these changes

2021-06-02 17:39 UTC, merged