feat: Creates section header component
chatwoot/chatwoot pull request #2296
Opened 2021-05-18 08:32 UTC by iamsivin

<img width="993" alt="Screenshot 2021-05-18 at 2 02 09 PM" src="https://user-images.githubusercontent.com/64252451/118618845-a7763a80-b7e1-11eb-9097-8af0cea2e96b.png">

2021-05-18 14:17 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/SectionHeader.vue
> +    padding: var(--space-smaller) 0;
Can we remove this so that default margin bottom will be used?

2021-05-18 14:17 UTC, nithindavid requested changes

2021-05-18 14:17 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/SectionHeader.vue
> +    margin-top: var(--space-smaller);
Please remove this too.

2021-05-18 18:20 UTC, nithindavid approved these changes

2021-05-18 18:20 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/SectionHeader.vue
> +  padding: var(--space-small);
Keep `space-normal` for outer containers.

2021-05-18 18:20 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/SectionHeader.vue
> +    .buttons {
Give more meaningful names with context `event-pill` or similar

2021-05-19 08:09 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/contacts/components/SectionHeader.vue
> +        Activities
Use `i18n`

2021-05-22 09:39 UTC, nithindavid approved these changes

2021-05-24 17:07 UTC, nithindavid requested changes

2021-05-24 17:07 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/SectionHeader.vue
> +        label="events"
I think we don't need this prop, please check other button also ?

2021-05-24 17:07 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/SectionHeader.vue
> +      margin-right: var(--space-one);
use `space-small`

2021-05-26 10:32 UTC, nithindavid requested changes

2021-05-26 10:32 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/SectionHeader.vue
> +        label="conversations"
Can we remove this prop? It's not needed I guess.

2021-05-28 16:52 UTC, nithindavid approved these changes

2021-05-31 04:37 UTC, merged