feature: Edit webhook URL
chatwoot/chatwoot pull request #2316
Opened 2021-05-21 08:53 UTC by muhsin-k

Fixes #1878

2021-05-24 07:37 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/settings/integrations/EditWebHook.vue
> +    },
Please use the mixin.

2021-05-24 07:37 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/settings/integrations/EditWebHook.vue
> +        this.addWebHook.showLoading = false;
this can be moved to `finally` block

2021-05-25 18:20 UTC, muhsin-k commented
@pranavrajs Requested changes are done

2021-05-28 16:51 UTC, nithindavid requested changes

2021-06-02 16:06 UTC, pranavrajs submitted a review, later dismissed
Please add specs for mutations/actions. Otherwise looks good.

2021-06-04 09:07 UTC, pranavrajs submitted a review, later dismissed

2021-06-04 09:07 UTC, pranavrajs commented
@muhsin-k Seems like there is a conflict, can you please fix it?

2021-06-06 11:29 UTC, merged