feat: Ability to add label for contact page
chatwoot/chatwoot pull request #2350
Opened 2021-05-28 18:05 UTC by iamsivin

2021-06-09 06:06 UTC, nithindavid requested changes

2021-06-09 06:06 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ContactLabels.vue
> +        return this.allLabels.find(x => x.title === e);
Please consider meaningful variable names for `x, e`

2021-06-09 08:07 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/contacts/components/ContactLabels.vue
> +        // Ignore error
Should we actually show an error if update didn't work?

2021-06-09 08:09 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/contactLabels.js
> +import * as types from '../mutation-types';
Please use `import types from '../mutation-types` and `types.SET_CONTACT_LABELS_UI_FLAG` instead of `types.default.SET_CONTACT_LABELS_UI_FLAG`

2021-06-09 08:12 UTC, pranavrajs commented on app/javascript/dashboard/i18n/locale/en/contact.json
> +        }
Do we actually use these keys?

2021-06-09 08:13 UTC, pranavrajs requested changes
Nice work! Please take a look at the individual comments.

2021-06-10 02:51 UTC, iamsivin commented on app/javascript/dashboard/i18n/locale/en/contact.json
> +        }
No, I will remove the unused keys.

2021-06-10 06:18 UTC, muhsin-k commented on app/javascript/dashboard/api/contacts.js
> +
Add specs for `getContactLabels` and `updateContactLabels` methods

2021-06-10 09:53 UTC, pranavrajs commented
<img width="528" alt="Screenshot 2021-06-10 at 3 17 51 PM" src="https://user-images.githubusercontent.com/2246121/121504401-9cd54c80-c9ff-11eb-9270-bdb84d3e6681.png">

Just tested it out. There is a horizontal scroll on the label dropdown. Also, there are a couple of errors on the console. @iamsivin Can you please take care of that as well?

2021-06-11 11:15 UTC, iamsivin commented
> <img alt="Screenshot 2021-06-10 at 3 17 51 PM" width="528" src="https://user-images.githubusercontent.com/2246121/121504401-9cd54c80-c9ff-11eb-9270-bdb84d3e6681.png">
> 
> Just tested it out. There is a horizontal scroll on the label dropdown. Also, there are a couple of errors on the console. @iamsivin Can you please take care of that as well?

I have fixed these issues in the last commit.

2021-06-14 04:30 UTC, nithindavid approved these changes

2021-06-14 05:06 UTC, merged