Enhancement: force user to type name before inbox/team delete
chatwoot/chatwoot pull request #2370
Opened 2021-06-03 08:43 UTC by muhsin-k

Fixes #2369

2021-06-03 15:48 UTC, nithindavid requested changes

2021-06-03 15:48 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/modal/ConfirmDeleteModal.vue
> +          :disabled="!value || !$v.value.isEqual"
We have `is-disabled` will take care of css styles.

2021-06-03 15:48 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/modal/ConfirmDeleteModal.vue
> +          color-scheme="secondary"
color-scheme => alert

2021-06-03 15:48 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/modal/ConfirmDeleteModal.vue
> +          class="alert nice"
This can be omitted.

2021-06-03 17:52 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/modal/ConfirmDeleteModal.vue
> +        :placeholder="cofirmPlaceHolderText"
Spelling mistake

2021-06-03 17:54 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/modal/ConfirmDeleteModal.vue
> +    <form @submit.prevent="onConfirm()">
`onConfirm` should be enough `onConfirm()` is not needed.

2021-06-03 17:55 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/modal/ConfirmDeleteModal.vue
> +          :is-disabled="!value || !$v.value.isEqual"
Can't we have something like `$v.error` for the entire form? What I meant is that if and only if form is valid condition can be used here.

2021-06-03 17:55 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/modal/ConfirmDeleteModal.vue
> +    },
Can we use $emit events instead of passing function prop down to the component?

2021-06-03 17:56 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/modal/ConfirmDeleteModal.vue
> +        if (value !== this.confirmValue) {
`return value === this.confirmValue;` is enough right?

2021-06-03 17:57 UTC, pranavrajs requested changes
Nice work! I have some individual comments.

2021-06-04 07:47 UTC, pranavrajs approved these changes

2021-06-04 07:47 UTC, merged