chore: Add different color for messages from bot
chatwoot/chatwoot pull request #2374
Opened 2021-06-03 15:58 UTC by nithindavid

Users will be able to easily distinguish agent messages with ones sent by bots.

**Preview**
![image](https://user-images.githubusercontent.com/1277421/120675190-7b7dd900-c4b2-11eb-9869-d185a5703721.png)

2021-06-03 18:15 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/conversation/Message.vue
> +      return !this.sender.type || this.sender.type === 'bot';
sender can be null

2021-06-03 18:16 UTC, pranavrajs approved these changes

2021-06-04 07:35 UTC, sojan-official approved these changes

2021-06-04 07:43 UTC, muhsin-k approved these changes

2021-06-04 08:50 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/conversation/Message.vue
> +      return !this.sender.type || this.sender.type === 'bot';
@nithindavid Sorry about this, this was not needed. This was handled already in the computed property.

2021-06-04 09:00 UTC, pranavrajs requested changes
On QA, I found that the message turns violet first and then becomes blue. Please see the attached video.


https://user-images.githubusercontent.com/2246121/120775981-5e441b80-c541-11eb-8e16-33bd6e6343b9.mp4

2021-06-04 10:30 UTC, nithindavid commented
@pranavrajs Thank for pointing out! I have added the fix.

2021-06-04 16:23 UTC, pranavrajs approved these changes

2021-06-04 16:24 UTC, merged