feat: notification audio alert
chatwoot/chatwoot pull request #2415
Opened 2021-06-11 07:41 UTC by iamsivin

2021-06-22 16:17 UTC, nithindavid requested changes

2021-06-22 16:17 UTC, nithindavid commented on app/javascript/shared/helpers/AudioNotificationHelper.js
> +  userId = assignee.id;
This is not needed I think as `userId` and `id` will always have same value.

2021-06-22 16:17 UTC, nithindavid commented on app/javascript/shared/helpers/AudioNotificationHelper.js
> +    userId,
We should be using `currentUserId` instead of `userId` . See my above comment.

2021-06-24 06:06 UTC, iamsivin commented
@pranavrajs  I have fixed the reviews comments.

2021-06-25 07:42 UTC, nithindavid requested changes

2021-06-25 07:42 UTC, nithindavid commented on app/javascript/shared/helpers/AudioNotificationHelper.js
> +  return id;
```suggestion
  if (currentConv.meta) {
    const { assignee = {} }= currentConv.meta;
    const { id } = assignee;
    return id;
  }
  return undefined;
```

2021-06-25 07:42 UTC, nithindavid commented on app/javascript/shared/helpers/AudioNotificationHelper.js
> +  return id;
Please write a spec for this function.

2021-07-05 06:16 UTC, pranavrajs approved these changes

2021-07-05 06:31 UTC, merged