feat: Creates new component for multiselect.
chatwoot/chatwoot pull request #2446
Opened 2021-06-17 10:11 UTC by iamsivin

https://user-images.githubusercontent.com/64252451/122377140-6f9a1880-cf82-11eb-9048-8b55cb42503b.mov

2021-06-17 14:45 UTC, muhsin-k commented on app/javascript/shared/components/ui/MutiselectDropdown.vue
> +        v-if="value && value.name && value && value.id"
Use computed property.

2021-06-17 14:45 UTC, muhsin-k commented on app/javascript/shared/components/ui/MutiselectDropdown.vue
> +        :src="value && value.thumbnail"
Use `value.thumbnail` directly since you are already checking the value is exist or not using `v-if`

2021-06-17 14:45 UTC, muhsin-k commented on app/javascript/shared/components/ui/MutiselectDropdown.vue
> +    value: {
Use meaningful name for prop ex: `selectedItem` or `selectedOption`

2021-06-17 14:46 UTC, muhsin-k commented on app/javascript/shared/components/ui/MultiselectDropdownItems.vue
> +        placeholder="Filter"
`i18n`

2021-06-17 14:47 UTC, muhsin-k commented on app/javascript/shared/components/ui/MultiselectDropdownItems.vue
> +    value: {
User meaningful name for the prop. `selectedOption` or `selectedItem`

2021-06-17 14:48 UTC, muhsin-k reviewed
@iamsivin Nice work. Please see the inline comments

2021-06-21 10:15 UTC, muhsin-k commented on app/javascript/shared/components/ui/MutiselectDropdown.vue
> +        this.selectedItem.id
Used `this.selectedItem` multiple times. Can we use a condition something like`this.selectedItem && this.selectedItem.id`

2021-06-25 07:24 UTC, nithindavid requested changes

2021-06-25 07:24 UTC, nithindavid commented on app/javascript/shared/components/ui/MutiselectDropdown.vue
> +            v-if="!isValueExist"
`isValueExist` => `hasValue`

2021-06-25 12:10 UTC, nithindavid approved these changes

2021-06-25 12:11 UTC, merged