feat: Update agent and team multi-select with new multi-select dropdown
chatwoot/chatwoot pull request #2516
Opened 2021-06-25 15:33 UTC by iamsivin

https://user-images.githubusercontent.com/64252451/123448213-4b7cae00-d5f8-11eb-95d1-b23530794ff5.mov

Fixes #2476

2021-07-01 08:15 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
> +import multiselectDropdown from 'shared/components/ui/MutiselectDropdown.vue';
Component name always should be in [**PascalCase**](https://vuejs.org/v2/style-guide/#Component-name-casing-in-JS-JSX-strongly-recommended)

2021-07-01 08:16 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
> +import multiselectDropdown from 'shared/components/ui/MutiselectDropdown.vue';
import MultiselectDropdown from 'shared/components/ui/MutiselectDropdown.vue';

2021-07-15 08:05 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/conversation/ContactPanel.vue
> +      return this.assignedAgent;
Return is not needed this and below method

2021-07-15 08:12 UTC, nithindavid requested changes

2021-07-15 08:12 UTC, nithindavid commented on app/javascript/shared/components/ui/MultiselectDropdownItems.vue
> +      )[this.arrowIndex];
This is creating a conflict when navigating with up/down keys after tab press. We need to keep them in sync.

2021-07-22 14:31 UTC, nithindavid commented on app/javascript/shared/components/ui/MultiselectDropdownItems.vue
> +      const lastElementIndex = [...array].indexOf(lastElement);
```suggestion
      const lastElementIndex = array.length -1 
```

2021-07-22 14:31 UTC, nithindavid commented on app/javascript/shared/components/ui/MultiselectDropdownItems.vue
> +      const array = this.$refs.multiselectDropdown.querySelectorAll(
Lets come up with a better name for `array`

2021-07-22 14:32 UTC, nithindavid requested changes
Please see the comments.

2021-07-26 16:29 UTC, nithindavid approved these changes

2021-07-29 12:14 UTC, merged