feat: One off campaign UI
chatwoot/chatwoot pull request #2621
Opened 2021-07-14 06:15 UTC by muhsin-k

2021-07-15 06:16 UTC, nithindavid commented on app/javascript/dashboard/components/ui/DatePicker.vue
> +        yesterday.setDate(yesterday.getDate() - 1);
https://date-fns.org/v2.22.1/docs/addDays

2021-07-15 06:24 UTC, nithindavid requested changes

2021-07-15 06:24 UTC, nithindavid commented on app/javascript/dashboard/components/ui/DatePicker.vue
> +      :type="type"
Can we keep date range and date picker as separate components to keep it simple.

2021-07-15 06:24 UTC, nithindavid commented on app/javascript/dashboard/components/ui/DatePicker.vue
> +      :type="type"
If a future case comes up, we have to always check the type is Array or date depending on functionality.

2021-07-15 06:24 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/settings/inbox/components/AddCampaign.vue
> +      let campaignDetails = null;
Moving the `campaignDetails` logic to a new method/computed would be good.

2021-07-15 06:25 UTC, nithindavid commented
NIce work :) Added some minor comments.

2021-07-15 08:00 UTC, nithindavid approved these changes

2021-07-15 08:01 UTC, muhsin-k commented
@nithindavid Please check the latest changes

2021-07-15 08:01 UTC, merged

2021-08-02 12:55 UTC, tabrza commented
would be worth having the ability to link to the website wherever the chat widget is integrated and have it pre-opened in order to encourage engaging in a new conversation. this could be an option should the campaign creator wish so