Removing duplicate callback to create auth token
chatwoot/chatwoot pull request #2624
Opened 2021-07-14 10:16 UTC by mrunalselokar

## Description
Removed after create callback in user model to create a new access token. This is already being taken care of by  `AccessTokenable` module.

Fixes # ([Two access tokens created for each new user #2620 ](https://github.com/chatwoot/chatwoot/issues/2620))

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Updated `user_spec.rb` to verify that only a single auth token is created for a newly created user.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-07-14 10:21 UTC, pranavrajs commented
@mrunalselokar Thanks for the PR 👍. 

@sojan-official Please take a look at this and see if we can get it merged soon.

2021-07-14 10:44 UTC, sojan-official requested changes
@mrunalselokar  Thanks for the changes.  I have added a minor comment on the specs. 
Also could you add a data migration for removing the duplicate access tokens for the existing user account ? 

Let me know if you need help with that.

2021-07-14 10:44 UTC, sojan-official commented on spec/models/user_spec.rb
> +      token_count = AccessToken.where(owner_id: new_user.id).count
```suggestion
      token_count = AccessToken.where(owner: new_user).count
```

`owner` attribute is a polymorphic column. so we should pass both `owner_id` and `owner_type`, or pass the object and rails takes care of it for us.

2021-07-14 13:05 UTC, sojan-official commented
@mrunalselokar  Thanks for the quick updates. The changes look good to me. We will test it against a staging database and get this merged.

2021-07-14 13:08 UTC, sojan-official approved these changes

2021-07-15 06:11 UTC, muhsin-k approved these changes

2021-07-15 06:12 UTC, muhsin-k commented
@sojan-official QA has been done on staging and everything is working as expected.

2021-07-15 09:54 UTC, merged