feat: CSAT for all channels
chatwoot/chatwoot pull request #2749
Opened 2021-08-03 19:17 UTC by muhsin-k

Fixes #2653

2021-08-14 17:56 UTC, sojan-official reviewed
The code looks good to me. Let's do a round of testing for the behavior on all channels and get this merged. 

- shouldn't get triggered for tweet conversations

2021-08-14 17:56 UTC, sojan-official commented on app/models/message.rb
> +    "Please rate this conversation , #{ENV['FRONTEND_URL']}/survey/responses/#{conversation.uuid}"
Lets add translations for this

2021-08-15 07:26 UTC, sojan-official commented
@pranavrajs  @muhsin-k  we might need to revisit whether we should start new conversations for Facebook and Twitter on resolution.

2021-08-20 18:43 UTC, sojan-official commented
## email 

<img width="846" alt="Screenshot 2021-08-21 at 12 08 47 AM" src="https://user-images.githubusercontent.com/73185/130279055-5e5868b2-242c-4c02-9944-79e964ef478e.png">

## response page

<img width="800" alt="Screenshot 2021-08-21 at 12 08 38 AM" src="https://user-images.githubusercontent.com/73185/130279058-969e5e37-c9e9-4861-bd9e-ba9e363df823.png">

2021-08-20 18:43 UTC, sojan-official submitted a review, later dismissed

2021-08-22 18:23 UTC, sojan-official commented
@nithindavid  could you take a look at the front end code, if it's all good let's get this merged?

2021-08-23 05:08 UTC, nithindavid requested changes
@muhsin-k Nice work :D I have left some minor comments

2021-08-23 05:08 UTC, nithindavid commented on app/javascript/survey/views/Response.vue
> +    enableBanner() {
Would be nice to see `isSomething` pattern being followed like other functions to keep it consisent.

2021-08-23 05:08 UTC, nithindavid commented on app/javascript/survey/components/Feedback.vue
> +      class="flex items-center font-medium float-right"
We could avoid float classes as we have flex styles. We could wrap it in a div to float it right.

2021-08-23 12:03 UTC, nithindavid approved these changes

2021-08-23 16:30 UTC, merged