feat: Creates cc bcc input component story for reply box
chatwoot/chatwoot pull request #2763
Opened 2021-08-06 11:07 UTC by nithindavid

![image](https://user-images.githubusercontent.com/1277421/128501359-f32be14f-6834-4c95-a4c3-6ca4a581e11b.png)

2021-08-09 07:52 UTC, muhsin-k commented on app/javascript/dashboard/components/widgets/conversation/stories/ReplyEmailHead.stories.js
> +import AddReminder from '../ReplyEmailHead';
```suggestion
import ReplyEmailHead from '../ReplyEmailHead';
```

2021-08-09 07:53 UTC, muhsin-k commented on app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
> +        <label class=" input-group-label">
Space before classname

2021-08-09 07:53 UTC, muhsin-k commented on app/javascript/dashboard/components/widgets/conversation/ReplyEmailHead.vue
> +        <label class=" input-group-label">
Space before classname

2021-08-09 07:54 UTC, muhsin-k requested changes
@nithindavid Nice work. Please see the inline comments

2021-08-09 09:23 UTC, nithindavid commented
@muhsin-k thanks for the review,  I have made the changes.

2021-08-09 10:01 UTC, muhsin-k commented on app/javascript/dashboard/components/widgets/conversation/stories/ReplyEmailHead.stories.js
> +  components: { AddReminder },
```suggestion
  components: { ReplyEmailHead },
```

2021-08-09 10:01 UTC, muhsin-k commented on app/javascript/dashboard/components/widgets/conversation/stories/ReplyEmailHead.stories.js
> +    '<add-reminder v-bind="$props" @add="onAdd" @click="onClick"></add-reminder>',
```suggestion
    '<reply-email-head v-bind="$props" @add="onAdd" @click="onClick"></reply-email-head>',
```

2021-08-09 10:01 UTC, muhsin-k commented on app/javascript/dashboard/components/widgets/conversation/stories/ReplyEmailHead.stories.js
> +  component: AddReminder,
```suggestion
  component: ReplyEmailHead,
```

2021-08-10 16:26 UTC, muhsin-k approved these changes

2021-08-11 06:04 UTC, merged