fix: Use label for "Subscribe to updates" checkbox
chatwoot/chatwoot pull request #2788
Opened 2021-08-11 10:55 UTC by paescuj

# Pull Request Template

## Description

This makes the description text for the "Subscribe to updates" checkbox on the onboarding page clickable and is semantically more correct.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested locally

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-08-11 13:28 UTC, nithindavid requested changes
Thanks for the PR @paescuj, I have a minor comment. Please see it

2021-08-11 13:28 UTC, nithindavid commented on app/views/installation/onboarding/index.html.erb
> +                  <label for="subscribe_to_updates">
Can we use a class name here for this label and write target style for it to avoid the `!important`?

2021-08-11 15:41 UTC, nithindavid submitted a review, later dismissed
🎉

2021-08-11 20:27 UTC, sojan-official commented
@nithindavid should we do some additional styling. the position of the checkbox seems slightly off.


## Original 
<img width="884" alt="Screenshot 2021-08-12 at 1 55 17 AM" src="https://user-images.githubusercontent.com/73185/129098200-67616eb8-33e7-4c57-9517-255ab9745fd7.png">


## Current with change
<img width="950" alt="Screenshot 2021-08-12 at 1 55 07 AM" src="https://user-images.githubusercontent.com/73185/129098197-8084aa16-0944-46c9-add9-a0b0833d578e.png">

2021-08-12 10:49 UTC, nithindavid commented
@paescuj Can you please fix the spacing issue mentioned by @sojan-official ? Let me know if you need help.

2021-08-13 12:20 UTC, paescuj commented
> @paescuj Can you please fix the spacing issue mentioned by @sojan-official ? Let me know if you need help.

The problem was that other CSS rules still had a higher specificity (and were overriding the bottom margin), so I've nested `.update-subscription--checkbox` in `.superadmin-body`. Now it's working for me (Firefox).

2021-08-13 13:29 UTC, sojan-official commented
@paescuj looks good to me. thanks a lot for picking this up. 

<img width="1041" alt="Screenshot 2021-08-13 at 6 59 03 PM" src="https://user-images.githubusercontent.com/73185/129364388-dd7fd84f-6be7-4a14-98ad-fc2ea04a9460.png">

2021-08-13 13:32 UTC, paescuj commented
> @paescuj looks good to me. thanks a lot for picking this up.
> 
> <img alt="Screenshot 2021-08-13 at 6 59 03 PM" width="1041" src="https://user-images.githubusercontent.com/73185/129364388-dd7fd84f-6be7-4a14-98ad-fc2ea04a9460.png">

Great! 👍 You're very welcome!

2021-08-13 13:40 UTC, merged