enhancement: Creates draggable pop out replay box
chatwoot/chatwoot pull request #2832
Opened 2021-08-16 11:27 UTC by iamsivin

Fixes #2784 

https://user-images.githubusercontent.com/64252451/129556559-568d9d11-07b0-43ae-8d03-a9f439e5609b.mov

2021-08-16 15:37 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +  box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
Use existing css variables for shadow.

2021-08-16 15:38 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +      draggableReplayBox: false,
`isReplyBoxFloating`

2021-08-16 15:41 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +Vue.component('vue-draggable-resizable', VueDraggableResizable);
We could omit this and use it with
```
export default {
  components: {
    Message,
    ReplyBox,
  },
```

2021-08-16 15:42 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +            alt="Someone is typing"
`i18n`

2021-08-16 15:45 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +            alt="Someone is typing"
Typing indicator code is being repeated, Can we use a better approach.

2021-08-16 15:48 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +        class-names="expand-icon"
Instead of expand can we come up with something like `popout` or `float`

2021-08-16 15:49 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +      class-name="draggable-Replay-box"
Replace all occurrences of `Replay` => `reply`

2021-08-16 15:50 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +      <reply-box
This component is being repeated, Can we use a better approach

2021-08-16 15:50 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +  top: -4px;
Use css variable

2021-08-16 15:51 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +  z-index: 10;
create a variable for z-index.

2021-08-16 15:51 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +  position: absolute;
We could use flex to position this button

2021-08-16 15:52 UTC, nithindavid requested changes
See the inline comments

2021-08-16 15:56 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +  box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
reply instead of `replay`

2021-08-18 10:10 UTC, muhsin-k commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +    onClickPopoutReplyBox() {
```suggestion
    showPopoutReplyBox() {
```

2021-08-18 10:10 UTC, muhsin-k commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +    onClickClosePopoutReplyBox() {
```suggestion
    closePopoutReplyBox() {
```

2021-08-18 10:10 UTC, muhsin-k commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +        this.onClickClosePopoutReplyBox();
```suggestion
        this.closePopoutReplyBox();
```

2021-08-18 10:16 UTC, muhsin-k commented on app/javascript/dashboard/components/widgets/WootWriter/ReplyTopPanel.vue
> +      icon="ion-arrow-expand"
@nithindavid Is `ion-arrow-resize` better?

2021-08-31 05:44 UTC, muhsin-k submitted a review, later dismissed

2021-09-01 04:40 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
> +      width: 104rem;
```suggestion
      max-width: 104rem;
      width: 60%;
```

2021-09-01 13:41 UTC, nithindavid approved these changes

2021-09-01 13:42 UTC, merged