Update on agent mention email template
chatwoot/chatwoot pull request #2838
Opened 2021-08-17 11:26 UTC by tejaswinichile

## Description

Updated a template for the conversation_mention email. We have introduced in MessageDrop to get the message sender and message content in the template. This is not impacting other ConversationNotificationsMailer templates.

Fixes #2825 

## Type of change

Please delete options that are not relevant.

- [-] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

1. Mention agent in the conversation, checked updated mail body. 
2. Assign agent and checked the relevant template if it's not impacted.

## Checklist:

- [-] My code follows the style guidelines of this project
- [-] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [-] My changes generate no new warnings
- [-] I have added tests that prove my fix is effective or that my feature works
- [-] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-08-17 15:57 UTC, pranavrajs requested changes
@tejaswinichile Nice work! One minor change is required. Please see the comment.

2021-08-17 16:35 UTC, tejaswinichile commented
@pranavrajs Made the changes in the mailer template and the regex.
<img width="799" alt="Screenshot 2021-08-17 at 2 57 29 PM" src="https://user-images.githubusercontent.com/10827585/129763217-4f03a458-2ec9-4aa5-8f27-924a567dda39.png">

2021-08-17 16:53 UTC, pranavrajs commented
Looks good to me. @sojan-official Does message drop has any effect on the outgoing email messages since we use liquid templates there also?

2021-08-18 06:19 UTC, tejaswinichile commented
@pranavrajs @sojan-official  I have tested other ConversationNotificationsMailer templates, i.e conversation_assignment and assigned_conversation_new_message. It's not being impacted by the current liquid_droppables change.
Please check.
<img width="1284" alt="Screenshot 2021-08-18 at 11 47 15 AM" src="https://user-images.githubusercontent.com/10827585/129847653-61ba4568-9b7f-4889-8938-8b7943354fef.png">
<img width="1284" alt="Screenshot 2021-08-18 at 11 48 07 AM" src="https://user-images.githubusercontent.com/10827585/129847663-9676e1b0-170d-4eaf-83f7-f492476d7560.png">

2021-08-18 07:24 UTC, pranavrajs commented
@tejaswinichile Please check the conversation reply mailers. 

1. Create a conversation in the web widget/email channel.
2. Reply to the conversation from the agent dashboard. 
3. Verify that the mail content is correct in the letter opener.

2021-08-18 07:50 UTC, tejaswinichile commented
@pranavrajs When the agent sends a reply to the conversation, an email related to the whole conversation gets created. Which is not impacted by the current change. 
<img width="420" alt="Screenshot 2021-08-18 at 1 16 01 PM" src="https://user-images.githubusercontent.com/10827585/129859436-a12f0d3b-497d-45b8-a2e7-52ead2d445fa.png">

2021-08-18 08:01 UTC, sojan-official approved these changes
LGTM

2021-08-18 09:30 UTC, pranavrajs approved these changes

2021-08-18 09:58 UTC, merged