feat: Creates a modal that add the ability to create a new custom attribute
chatwoot/chatwoot pull request #2903
Opened 2021-08-29 06:43 UTC by iamsivin

# Pull Request Template

## Description

Add the ability to create a new custom attribute

Fixes #2866 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please import `import attributes from './attributes/attributes.routes';` and add `...attributes.routes,` in `settings.routes.js` file.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-30 14:18 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttributes.vue
> +        <div v-if="hasValue" class="medium-12 columns">
```suggestion
        <div v-if="displayName" class="medium-12 columns">
```

2021-08-30 14:19 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttributes.vue
> +        },
Add `date`
```
{
  id: 5,
  option: "Date"
}
```

2021-08-30 14:19 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttributes.vue
> +    convertToSlug() {
```suggestion
    attributeKey() {
```

2021-08-30 14:19 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttributes.vue
> +    hasValue() {
I think this computed property is not needed. Just add a condition `displayName` is exist or not in the template

2021-08-30 14:19 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttributes.vue
> +      bus.$emit('newToastMessage', message);
use `alertMixin`

2021-08-30 14:19 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttributes.vue
> +        this.showAlert(this.$t('ATTRIBUTES_MGMT.ADD.API.SUCCESS_MESSAGE'));
Show all messages in `finally` block
For ex:
```
 try {
 	await this.$store.dispatch('attributes/create', {
 		attribute_display_name: this.displayName,
 		attribute_description: this.description,
 		attribute_model: this.attributeModel,
 		attribute_display_type: this.attributeType,
 		attribute_key: this.convertToSlug,
 	});
 	this.alertMessage = this.$t('ATTRIBUTES_MGMT.ADD.API.SUCCESS_MESSAGE');
 	this.onClose();
 } catch (error) {
 	const errorMessage = error?.response?.data?.message;
 	this.alertMessage =
 		errorMessage || this.$t('ATTRIBUTES_MGMT.ADD.API.ERROR_MESSAGE');
 } finally {
 	this.showAlert(this.alertMessage);
 }
```

2021-08-30 14:19 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/attributes/AddAttributes.vue
> +      } catch (error) {
Check any error message that exists in the `error` object otherways show the default error message.

2021-08-30 14:19 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/attributes/Index.vue
> +import AddAttributes from './AddAttributes';
```suggestion
import AddAttribute from './AddAttribute';
```

2021-08-30 14:20 UTC, muhsin-k commented on app/javascript/dashboard/store/mutation-types.js
> +  SET_CUSTOM_ATTRIBUTES: 'SET_CUSTOM_ATTRIBUTES',
```suggestion
  SET_CUSTOM_ATTRIBUTE: 'SET_CUSTOM_ATTRIBUTE',
```

2021-08-30 14:20 UTC, muhsin-k requested changes
@iamsivin Nice work. Please see the inline comments

2021-08-31 05:33 UTC, muhsin-k approved these changes

2021-08-31 08:22 UTC, nithindavid approved these changes

2021-08-31 08:24 UTC, merged