feat: Add Command bar for improved productivity
chatwoot/chatwoot pull request #3352
Opened 2021-11-10 05:06 UTC by pranavrajs

Fixes #3335 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-10 05:57 UTC, nithindavid requested changes
Has a minor comment, otherwise looks good.

2021-11-10 05:57 UTC, nithindavid commented on app/javascript/dashboard/i18n/locale/en/generalSettings.json
> +      "ADD_LABEL": "Add label to the conversation",
```suggestion
      "ADD_LABEL": "Add labels to the conversation",
```

2021-11-10 05:57 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/commands/commandbar.vue
> +      placeholder: 'Search or jump to',
i18n ?

2021-11-10 06:55 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/commands/commandbar.vue
> +      placeholder: 'Search or jump to',
Yes, we need to, will move that.

2021-11-12 17:14 UTC, nithindavid approved these changes

2021-11-12 17:14 UTC, nithindavid commented
@pranavrajs Can you fix the code climate issues ?

2021-11-15 10:34 UTC, nithindavid approved these changes

2021-11-15 11:06 UTC, muhsin-k approved these changes

2021-11-15 11:52 UTC, merged