Add redirect link to conversation in success message
chatwoot/chatwoot pull request #3711
Opened 2022-01-07 21:41 UTC by ximenasandoval

# Pull Request Template

## Description

When creating a conversation from the contacts tab now we can go directly to the conversation by clicking the link in the success message.

Fixes #3063

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

https://user-images.githubusercontent.com/33427323/148610816-f1361469-d0af-4caf-94fa-b118582233f6.mov

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-07 21:54 UTC, pranavrajs commented
Thanks, @ximenasandoval, It looks like a nice feature to have. Please see the comments below around the implementation.

2022-01-07 22:19 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
> +      )}</a>
Passing an HTML seems a little off, can use additional params on the SnackBar component. Payload can be of the format.
```
{
   message: '',
   action: {
     type: 'link',
     to: '<link-to-url>'
   }
}
```

2022-01-07 22:21 UTC, pranavrajs requested changes
We can standardize the implementation so that we can solve similar use-cases easily.

2022-01-08 01:14 UTC, ximenasandoval commented
Hi! Thanks for the review! I'll change it 🙌🏽

2022-01-13 03:57 UTC, nithindavid requested changes
@ximenasandoval  This is a nice change! I have added a suggestion to make the link and text come in same line. Please see if it makes sense

2022-01-13 03:57 UTC, nithindavid commented on app/javascript/dashboard/i18n/locale/en/contact.json
> +      "GO_TO_CONVERSATION": "Go to conversation",
```suggestion
      "GO_TO_CONVERSATION": "VIEW",
```

2022-01-13 03:57 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/conversation/contact/ConversationForm.vue
> +           </br> <a href="/app/accounts/${
```suggestion
           <a href="/app/accounts/${
```

2022-01-13 04:07 UTC, nithindavid commented on app/javascript/dashboard/i18n/locale/en/contact.json
> +      "GO_TO_CONVERSATION": "Go to conversation",
Ignore if this is not in context with changes suggested by Pranav.

2022-01-13 04:14 UTC, ximenasandoval commented
Hi! Thanks for the review 😄 sure, I'll change it to display the message and link together!

2022-01-13 04:27 UTC, ximenasandoval commented
By double checking it would clash with the first changes suggested by Pranav 😲 it would change the payload.

2022-01-13 04:28 UTC, nithindavid commented
> By double checking it would clash with the first changes suggested by Pranav 😲 it would change the payload.

You can Ignore it 👍

2022-01-13 19:15 UTC, merged