Feat/add contact custom views
chatwoot/chatwoot pull request #3791
Opened 2022-01-18 03:18 UTC by iamsivin

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-18 04:35 UTC, nithindavid requested changes

2022-01-18 04:35 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
> +      filterType: 1,
Use this as a constant with name of constant referring to type of filter.

2022-01-18 04:35 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
> +      this.customViewsQuery = { payload: payload };
```suggestion
      this.customViewsQuery = { payload };
```

2022-01-18 04:35 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
> +          class="margin-right-small clear"
User variant for clear

2022-01-18 06:45 UTC, tejaswinichile approved these changes
LGTM 👍🏼

2022-01-18 07:35 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/contacts/components/ContactsView.vue
> +        @open-customview-modal="onClickOpenCustomViewsModal"
```suggestion
        @on-toggle-save-filter="onToggleSaveFilters"
```

2022-01-21 05:00 UTC, nithindavid approved these changes

2022-01-21 22:12 UTC, merged