Feature: Filtering conversations and contacts with custom attributes
chatwoot/chatwoot pull request #3851
Opened 2022-01-26 12:13 UTC by fayazara

# Pull Request Template

## Description

Adds support for filtering conversations and contacts with custom attributes

Fixes #3738 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-27 07:09 UTC, nithindavid requested changes

2022-01-27 07:09 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ContactsAdvancedFilters.vue
> +import * as OPERATORS from '../../../../components/widgets/FilterInput/FilterOperatorTypes';
Use absolute path here

2022-01-31 02:47 UTC, nithindavid requested changes

2022-01-31 02:47 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/conversation/ConversationAdvancedFilter.vue
> +import * as OPERATORS from '/app/javascript/dashboard/components/widgets/FilterInput/FilterOperatorTypes.js';
```suggestion
import * as OPERATORS from 'dashboard/components/widgets/FilterInput/FilterOperatorTypes';
```

2022-01-31 02:47 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/components/ContactsAdvancedFilters.vue
> +import * as OPERATORS from '/app/javascript/dashboard/components/widgets/FilterInput/FilterOperatorTypes.js';
```suggestion
import * as OPERATORS from 'dashboard/components/widgets/FilterInput/FilterOperatorTypes.js';
```

2022-01-31 02:47 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/contacts/contactFilterItems/index.js
> +} from '/app/javascript/dashboard/components/widgets/FilterInput/FilterOperatorTypes.js';
```suggestion
} from 'dashboard/components/widgets/FilterInput/FilterOperatorTypes.js';
```

2022-02-01 07:29 UTC, nithindavid approved these changes

2022-02-01 07:43 UTC, muhsin-k approved these changes
QA has been done on local environment and everything is working as expected.

2022-02-01 07:43 UTC, merged