Fix - Automation Bugs and minor enhancements
chatwoot/chatwoot pull request #3936
Opened 2022-02-08 11:14 UTC by fayazara

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #3935 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-02-08 15:29 UTC, nithindavid approved these changes

2022-02-09 09:08 UTC, pranavrajs commented
<img width="460" alt="Screenshot 2022-02-09 at 2 36 45 PM" src="https://user-images.githubusercontent.com/2246121/153162345-50b066d9-dd62-4ce5-a54d-02063d74018b.png">

@fayaz Add Condition Button is throwing this error.

2022-02-09 09:49 UTC, fayazara commented
@pranavrajs When did this occur exactly? I tried appending conditions and I didnt get the same error.

Maybe a specific `condition` caused this, what had you selected?

https://user-images.githubusercontent.com/15716057/153170946-f2b1183f-6c61-4da0-99a0-112b8cbe6db2.mp4

2022-02-09 09:51 UTC, pranavrajs commented
@fayazara 

Event: message_created
Filter: Message Contents
Operator: contains

2022-02-09 10:49 UTC, fayazara commented
> @fayazara
> 
> Event: message_created Filter: Message Contents Operator: contains

@pranavrajs Fixed this, it was occuring because automations was following a different format than the filters.

Also fixed another bug where the query_operator was coming blank in edit mode.

2022-02-14 05:58 UTC, nithindavid requested changes

2022-02-14 05:58 UTC, nithindavid commented on app/javascript/dashboard/routes/dashboard/settings/automation/EditAutomationRule.vue
> +      if (
Can we refactor into 

```
const { conditions } = this.automation;
const [lastCOndition] = conditions;
const lastQueryOperator = lastCOndition.query_operator
```

2022-02-15 17:13 UTC, muhsin-k submitted a review, later dismissed

2022-02-15 17:46 UTC, muhsin-k approved these changes

2022-02-15 18:06 UTC, merged