Adds a sort filter to inboxes array
chatwoot/chatwoot pull request #4383
Opened 2022-04-04 16:56 UTC by fayazara

# Pull Request Template

## Description

Sorts inboxes in the sidebar alphabetically

Fixes #4107

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-04-05 05:28 UTC, pranavrajs commented
<img width="180" alt="Screenshot 2022-04-05 at 10 51 57 AM" src="https://user-images.githubusercontent.com/2246121/161684286-5b0c5292-cf0d-4fe9-8715-3d8385b2e8d6.png">

@fayazara please check the lower case and uppercase ordering

2022-04-05 05:28 UTC, pranavrajs requested changes
Please check the comment.

2022-04-06 04:40 UTC, nithindavid approved these changes

2022-04-06 05:16 UTC, iamsivin approved these changes
Tested locally. LGTM 💯 

<img width="189" alt="image" src="https://user-images.githubusercontent.com/64252451/161900733-73c99d2d-6c12-4fe1-9548-8bfc43524789.png">


@fayazara Is it possible to add it to the inbox settings page also.

2022-04-06 09:17 UTC, pranavrajs approved these changes

2022-04-07 04:31 UTC, merged