chore: report improvements
chatwoot/chatwoot pull request #4392
Opened 2022-04-05 11:24 UTC by aswindevps

## Description

This change introduces new custom y-axis labels and custom tooltips for the below metrics in the report.

1. avg_first_response_time
2. avg_resolution_time

Fixes #https://github.com/chatwoot/product/issues/377

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2022-04-06 09:20 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
> +            }`;
Please use an i18n string here. 

<img width="347" alt="Screenshot 2022-04-06 at 2 49 46 PM" src="https://user-images.githubusercontent.com/2246121/161942044-d9dfbb37-b74a-48e6-9c1a-aae3936e7535.png">

2022-04-06 09:20 UTC, pranavrajs commented on app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
> +          },
Please use i18n here also.

2022-04-06 09:20 UTC, pranavrajs requested changes
Please see the inline comments.

2022-04-06 11:58 UTC, aswindevps commented on app/javascript/dashboard/routes/dashboard/settings/reports/components/WootReports.vue
> +          },
Done

2022-04-06 11:58 UTC, aswindevps commented on app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
> +            }`;
Done

2022-04-11 06:37 UTC, muhsin-k submitted a review, later dismissed

2022-04-11 15:27 UTC, pranavrajs approved these changes

2022-04-11 15:27 UTC, merged