Feat: Ability to configure an auto assignment limit for inboxes
chatwoot/chatwoot pull request #4672
Opened 2022-05-11 08:12 UTC by sojan-official

This PR introduces the ability of an admin to configure a max assignment limit for auto assignments at an inbox level. 
Once it is configured, an agent wouldn't be auto-assigned further conversations from that inbox, once their assignment limit is reached.

2022-05-11 08:34 UTC, sojan-official commented on app/helpers/api/v1/inboxes_helper.rb
> +  def account_channels_method
moved methods over her to satisfy rubocop

2022-05-11 08:34 UTC, sojan-official commented on app/controllers/application_controller.rb
> +  include Pundit::Authorization
fixing pundit deprecation warning

2022-05-11 08:35 UTC, sojan-official commented on app/controllers/api/v1/accounts/inboxes_controller.rb
> +Api::V1::Accounts::InboxesController.prepend_mod_with('Api::V1::Accounts::InboxesController')
will let us override methods in ee edition

2022-05-11 08:36 UTC, sojan-official commented on app/models/account.rb
> +Account.prepend_mod_with('Account')
following a unified style everywhere for prepend mod with

2022-05-13 08:05 UTC, vishnu-narayanan commented
@sojan-official If I understand correctly, `chatwootApp.enterprise?` is now relying on `DISABLE_ENTERPRISE` variable and/or the `enterprise` folder being present to enable/disable enterprise features. So at the moment, we will not be checking for a valid EE license to activate EE features?

2022-05-13 08:38 UTC, sojan-official commented
@vishnu-narayanan  That is correct. The license check will be implemented in the code and access to specific EE features will be limited by the features flags in the EE code.

2022-05-27 04:16 UTC, pranavrajs commented on enterprise/app/models/enterprise/inbox.rb
> +    conversations.open.select(:assignee_id).group(:assignee_id).having("count(*) > #{validated_limit}").filter_map(&:assignee_id)
Can't we use `>=` instead of `>`?

2022-06-07 11:04 UTC, sojan-official commented
- added validations for assignment limit
- 
![Screenshot 2022-06-07 at 4 34 05 PM](https://user-images.githubusercontent.com/73185/172364548-0b356ff8-6c5d-4e45-8ea3-c2c144e5f7b5.png)

2022-06-08 12:20 UTC, pranavrajs commented
@sojan-official A few issues.

### Round robin assignment logic

**✅ Case 1: If all agents in the team are online**

After reaching the capacity of all agents, the system should move the new conversations to the unassigned queue.

**❌ Case 2: If only a couple of agents in the team are online**

Consider a team with 2 people. 1 of them is online and the other is offline. In this case, once the online agent's capacity is reached, the system should keep the new conversations unassigned. 

Right now, it is assigning the conversations to the offline agent.

**❌ Case 3: If all the agents in the team are offline**

Ideally, this should not assign to any agent in the team, and the system should keep the conversations in the unassigned queue. We have the current behavior in the system assigning the conversations to offline agents. This needs to be updated to the case where offline agents would not be considered in round-robin assignment. 


### Validation issue in the frontend
<img width="646" alt="Screenshot 2022-06-08 at 5 48 44 PM" src="https://user-images.githubusercontent.com/2246121/172614387-958ecbc1-f7cf-4e41-a147-b0bb7ddd427f.png">

I can type any character in the input field and it doesn't show any error. The API calls don't pass this information to the backend. We need to add an additional validation to check whether the input is a number. Show error otherwise.

2022-06-08 12:21 UTC, pranavrajs requested changes
I have identified some issues, please take a look at the comment above.

2022-06-10 08:20 UTC, tejaswinichile submitted a review, later dismissed
LGTM 💯

2022-06-13 14:48 UTC, merged