Removes required validations for templates with no params
chatwoot/chatwoot pull request #4820
Opened 2022-06-08 13:45 UTC by fayazara

# Pull Request Template

## Description

Removes validation for whatsapp templates with no variables

Fixes #4819 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Created a mock template with no variables and sent the payload through

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-06-08 13:49 UTC, pranavrajs commented on app/javascript/dashboard/components/widgets/conversation/WhatsappTemplates/TemplateParser.vue
> -import { required } from 'vuelidate/lib/validators';
`requiredIf` is better instead of removing the required condition altogether, right?

2022-06-08 14:57 UTC, iamsivin approved these changes
Code LGTM 👍🏻

2022-06-09 14:21 UTC, pranavrajs commented on app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js
> +  locale: 'en',
Please remove these as well.

2022-06-09 14:22 UTC, pranavrajs commented on app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js
> +describe('whatsappTemplates', () => {
```suggestion
describe('#WhatsAppTemplates', () => {
```

2022-06-09 14:23 UTC, pranavrajs requested changes
I have minor suggestions, please take a look.

2022-06-09 14:26 UTC, fayazara commented on app/javascript/shared/mixins/specs/whatsappTemplates/whatsappTemplates.spec.js
> +
These were added by mistake, removing them

2022-06-09 14:29 UTC, fayazara commented
> I have minor suggestions, please take a look.

@pranavrajs Updated.

2022-06-09 16:04 UTC, pranavrajs approved these changes

2022-06-09 16:04 UTC, merged