feat: New sidebar component for help-center
chatwoot/chatwoot pull request #5017
Opened 2022-07-12 05:01 UTC by iamsivin

# Pull Request Template

Fixes https://github.com/chatwoot/product/issues/474

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

**Screenshot**

**Storybook view**

**NB:** Facing some issues with font and ul items not displaying correctly.

<img width="515" alt="Screenshot 2022-07-12 at 10 16 51 AM" src="https://user-images.githubusercontent.com/64252451/178411886-af04fa1d-262f-4186-a4ad-f2d9ad8750ec.png">

**Dashboard view**

<img width="293" alt="Screenshot 2022-07-12 at 9 53 20 AM" src="https://user-images.githubusercontent.com/64252451/178411872-def20718-3778-4417-a99c-d7d2cd52985f.png">

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-12 05:18 UTC, fayazara requested changes
Looks good. Left some small change comments.

2022-07-12 05:18 UTC, fayazara commented on app/javascript/dashboard/components/helpCenter/Sidebar/Sidebar.vue
> +  width: 24rem;
```suggestion
  width: var(--space-giga);
```

2022-07-12 05:18 UTC, fayazara commented on app/javascript/dashboard/components/helpCenter/Sidebar/SidebarSearch.vue
> +      placeholder="Search for articles"
i18n.

Also, why does this component exist? 
Since it is not emitting anything.

2022-07-12 06:10 UTC, nithindavid requested changes
Please see the minor comments

2022-07-12 06:10 UTC, nithindavid commented on app/javascript/dashboard/components/helpCenter/Sidebar/SidebarHeader.vue
> +        size="28px"
Why are the sizes are different for swap and up right?

2022-07-12 06:10 UTC, nithindavid commented on app/javascript/dashboard/components/helpCenter/Sidebar/SidebarHeader.vue
> +  height: 66px;
Update: The design is supposed to 64px, I'll update it. Meanwhile can you make it to 64?
```suggestion
  height: var(--space-jumbo);
```

2022-07-12 06:10 UTC, nithindavid commented on app/javascript/dashboard/components/helpCenter/Sidebar/SidebarHeader.vue
> +  padding: var(--space-normal) var(--space-zero);
```suggestion
  padding: var(--space-normal) 0;
```

2022-07-12 06:10 UTC, nithindavid commented on app/javascript/dashboard/components/helpCenter/Sidebar/SidebarSearch.vue
> +  height: 3.6rem;
```suggestion
  height: var(--space-large);
```

2022-07-12 06:10 UTC, nithindavid commented on app/javascript/dashboard/components/helpCenter/Sidebar/SidebarSearch.vue
> +  background: var(--s-50);
```suggestion
  background: var(--color-25);
```

2022-07-12 06:10 UTC, nithindavid commented on app/javascript/dashboard/components/helpCenter/Sidebar/SidebarSearch.vue
> +  border: 1px solid var(--s-100);
```suggestion
  border: 1px solid var(--s-50);
```

2022-07-12 06:10 UTC, nithindavid commented on app/javascript/dashboard/components/helpCenter/Sidebar/SidebarSearch.vue
> +  color: var(--s-200);
```suggestion
  color: var(--s-500);
```

2022-07-18 05:37 UTC, muhsin-k approved these changes

2022-07-18 05:46 UTC, merged