feat: Creates store to manage Portals API and data
chatwoot/chatwoot pull request #5020
Opened 2022-07-12 06:13 UTC by nithindavid

Creates the vue store design for the new portals.

This follows the https://redux.js.org/usage/structuring-reducers/normalizing-state-shape

2022-07-20 09:56 UTC, muhsin-k commented on app/javascript/dashboard/store/modules/helpCenterPortals/getters.js
> +  allHelpCenters: (...getterArguments) => {
Spec is missing for the getter `allHelpCenters`

2022-07-21 05:54 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +        commit('setHelpCenterUIFlag', {
Please use constants for the method names here.

2022-07-21 05:59 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +        commit('addHelpCenterEntry', helpCenter);
Let us not use the term help center. This is Portals API. Let us rename the variable to Portals.

2022-07-21 05:59 UTC, pranavrajs commented on app/javascript/dashboard/api/helpCenter/portals.js
> +class HelpCenterPortalsAPI extends ApiClient {
Please rename this to PortalsAPI.

2022-07-21 06:00 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/getters.js
> +  uiFlagsIn: _state => helpCenterId => {
Please use state. There is no need to use `_state`. `_` are generally used for private methods in js.

2022-07-21 06:07 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/getters.js
> +  totalHelpCentersCount: _state => _state.helpCenters.allIds.length || 0,
Just count is enough, right? `portals/count` is readable right?

2022-07-21 06:08 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +  fetchAllHelpCenters: async ({ commit }) => {
Let us follow the naming convention here. https://discord.com/channels/897869226579222540/999557432747503698/999557936294678539

2022-07-21 06:11 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +      throw new Error(error);
Please use the helper defined here https://github.com/chatwoot/chatwoot/blob/c0249a1b5b7ef83944d59a55e88dad8eab7b2ad3/app/javascript/dashboard/store/utils/api.js#L49-L57

2022-07-21 06:12 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +      throw new Error(error);
Please use the error helper defined here. 
https://github.com/chatwoot/chatwoot/blob/61055672384cb850415ebae70d7ccdc761bf3555/app/javascript/dashboard/store/utils/api.js#L59-L62

2022-07-21 06:12 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +      throw new Error(error);
Please update this on all the actions.

2022-07-21 06:15 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +      data.forEach(helpCenter => {
Wouldn't this trigger multiple renders in the UI? Can we do it in bulk?

2022-07-21 06:16 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/getters.js
> +  uiFlagsIn: _state => helpCenterId => {
Please update the names in the entire file.

2022-07-21 06:16 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/getters.js
> +    };
Can't we just return the object? This check and returning a new object seem unnecessary.

2022-07-21 06:19 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
> +    if (!helpCenterId) return;
Why do we need this check? Sending an update action without an id might not be done anywhere. Even if it was sent, the next line would catch it.

2022-07-21 06:20 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/mutations.js
> +    if (!helpCenterId) return;
This check seems unnecessary (Similar to the previous comment)

2022-07-21 06:21 UTC, pranavrajs requested changes
Please check the individual comments.

2022-07-25 10:52 UTC, muhsin-k commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +import HelpCenterPortalsAPI from 'dashboard/api/helpCenter/portals.js';
```suggestion
import PortalsAPI from 'dashboard/api/helpCenter/portals.js';
```

2022-07-25 10:52 UTC, muhsin-k commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +      const { data } = await HelpCenterPortalsAPI.get();
```suggestion
      const { data } = await PortalsAPI.get();
```

2022-07-25 10:52 UTC, muhsin-k commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +      const { data } = await HelpCenterPortalsAPI.create(params);
```suggestion
      const { data } = await PortalsAPI.create(params);
```

2022-07-25 10:52 UTC, muhsin-k commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +      const { data } = await HelpCenterPortalsAPI.update(helpCenter);
```suggestion
      const { data } = await PortalsAPI.update(helpCenter);
```

2022-07-25 10:54 UTC, muhsin-k approved these changes
Added a minor comment. PR looks good to me

2022-07-25 10:54 UTC, muhsin-k commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +      await HelpCenterPortalsAPI.delete(helpCenterId);
```suggestion
      await PortalsAPI.delete(helpCenterId);
```

2022-07-26 04:53 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +  fetchAllPortals: async ({ commit }) => {
```suggestion
  index: async ({ commit }) => {
```

2022-07-26 04:53 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +  createPortal: async ({ commit }, params) => {
```suggestion
  create: async ({ commit }, params) => {
```

2022-07-26 04:53 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +  updatePortal: async ({ commit }, { helpCenter }) => {
```suggestion
  update: async ({ commit }, { helpCenter }) => {
```

2022-07-26 04:53 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +  deletePortal: async ({ commit }, { helpCenterId }) => {
```suggestion
  delete: async ({ commit }, { helpCenterId }) => {
```

2022-07-26 04:59 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/helpCenterPortals/actions.js
> +      const { id: helpCenterId } = data;
portalId

2022-07-26 05:01 UTC, pranavrajs requested changes
@nithindavid There are references of helpCenter instead of portal. Please update those. Also, please update the actions to follow the naming convention. https://chatwoot.com/docs/handbook/engineering/frontend-guidelines#avoid-manipulating-dom-directly

2022-07-27 06:54 UTC, merged