Fixe 5138: Replace some packages with native functions
chatwoot/chatwoot pull request #5140
Opened 2022-07-28 14:00 UTC by KubesDavid

# Pull Request Template

## Description

Replace 'copy-text-to-clipboard', 'country-code-emoji' and 'query-string' packages with native functions.

Fixes #5138

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-07-28 14:38 UTC, pranavrajs commented on app/javascript/dashboard/helper/flag.js
> +export const getCountryFlag = countryCode => {
<img width="551" alt="Screenshot 2022-07-28 at 8 06 46 PM" src="https://user-images.githubusercontent.com/2246121/181556562-1fba7936-4b75-44aa-b1e4-354795b09c15.png">


Let us revert this change. The country-code-emoji does the exact same thing. I don't there is a significant advantage of us managing the code.

2022-07-28 14:41 UTC, pranavrajs commented
@KubesDavid Thanks for the suggestion and the PR. I think the changes in the PR don't make much difference in the bundle size as the packages (clipboard, country-code) are <0.5kb in size and (query-string) is only 2kb. 

Let me know if there is any other advantage you can see here.

2022-07-28 17:17 UTC, KubesDavid commented on app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfoRow.vue
> +      });
Good idea! Done.

2022-07-28 17:34 UTC, KubesDavid commented
My inspiration behind this PR is mainly the fact that only one feature is used from these packages, which is easy to replace. There is no need to add unnecessary packages to every single function, it avoids the mess in packages.json.

2022-08-01 13:40 UTC, pranavrajs commented
@iamsivin @fayazara Please test changes and see if we are good to merge this PR.

2022-08-02 09:16 UTC, fayazara commented on app/javascript/shared/helpers/clipboard.js
> +export const copyTextToClipboard = (
We can use ES6 standards here. 
```js
export const copyTextToClipboard = async (text) => {
    try {
        await navigator.clipboard.writeText(text);
    } catch (error) {
        throw `Unable to copy text to clipboard. Err: ${error}`;
    }
}
```

2022-08-02 09:17 UTC, fayazara requested changes
Left a comment. Please have a look.

2022-08-02 09:28 UTC, iamsivin reviewed
Please see the comments

2022-08-03 09:15 UTC, iamsivin approved these changes
LGTM

2022-08-03 11:38 UTC, merged