feat: Sets up portal public views with rails ERB and tailwind
chatwoot/chatwoot pull request #5309
Opened 2022-08-19 11:00 UTC by nithindavid

This PR sets up basic configurations to render help center home, articles.
This also includes 
1. rails turbo links
2. tailwind css

2022-08-22 04:00 UTC, pranavrajs commented on app/assets/stylesheets/portal/application.scss
> +@import "tailwindcss/base";
We are not using Rails Asset Pipeline, let us move this packs and import the pack in the layout file.

2022-08-22 04:01 UTC, pranavrajs commented on app/assets/stylesheets/portal/application.scss
> +@import "tailwindcss/base";
You have `app/javascript/portal/application.scss` already, so let us remove this.

2022-09-05 05:19 UTC, muhsin-k commented
@nithindavid The draft articles are also showing in public view https://www.loom.com/share/0ad279ba76e543e9a2db98dd816d025e

2022-09-09 13:39 UTC, tejaswinichile approved these changes

2022-09-09 16:31 UTC, fayazara requested changes
Have left a minor change comment. 

The rest of frontend looks good!

2022-09-12 12:49 UTC, tejaswinichile approved these changes

2022-09-12 14:05 UTC, iamsivin commented on app/views/public/api/v1/portals/articles/index.html.erb
> +					<div class="flex items-center md:space-x-2">
```suggestion
					<div class="flex items-center space-x-2">
```

2022-09-12 17:03 UTC, sojan-official approved these changes

2022-09-12 18:06 UTC, merged