fix: Save reaction in whatsapp message content
chatwoot/chatwoot pull request #5541
Opened 2022-10-03 15:51 UTC by tejaswinichile

# Pull Request Template

## Description

Save the message when `message_type: reaction`

Fixes #5539 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested on local and added the test cases for the same.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-11 07:38 UTC, tejaswinichile commented
@sojan-official I have made the respective changes as discussed.
Added the test cases to prove that we are ignoring reaction-type messages as well as not raising any errors for the same.

2022-10-12 07:14 UTC, sojan-official requested changes

2022-10-12 07:34 UTC, tejaswinichile commented on spec/jobs/webhooks/whatsapp_events_job_spec.rb
> +      expect(Message.last.content).to be_nil
@sojan-official Made the respective changes.

2022-10-12 08:05 UTC, muhsin-k submitted a review, later dismissed

2022-10-13 07:40 UTC, sojan-official commented on app/services/whatsapp/incoming_message_base_service.rb
> +    return if %w[text button interactive reaction].include?(message_type)
do we need this check ?

2022-10-13 07:44 UTC, tejaswinichile commented
Note: We will be taking care of https://sentry.io/share/issue/128633bcfc274c07828021dd3d28933e/ this issue in this current change.

2022-10-13 20:31 UTC, merged