fix: Send message with "enter" also do new line
chatwoot/chatwoot pull request #5961
Opened 2022-11-28 01:42 UTC by iamsivin

# Pull Request Template

Fixes https://github.com/chatwoot/chatwoot/issues/5622

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)

## How Has This Been Tested?

1. Enable enter to send messages in profile settings.
2. And write "something" to test in rich editor.
3. And move the cursor to "someth | ing" and press enter key.
4. See the sent message.
5. Now it will be "someth ing" before it will break the line "someth
                                                                                                   ing"

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-11-29 14:15 UTC, nithindavid requested changes

2022-11-29 14:15 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
> +    handleEnterKeyWhenEnterToSendEnabled(event) {
Found a bug on the help center article editor - https://www.loom.com/share/11f005fa91144b8cb9e089d7c38e4b37

2022-12-02 08:43 UTC, nithindavid requested changes

2022-12-02 08:43 UTC, nithindavid commented on app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
> +    isHelpCenter: { type: Boolean, default: false },
```suggestion
    overrideLineBreaks: { type: Boolean, default: false },
```

2022-12-02 08:47 UTC, iamsivin commented on app/javascript/dashboard/components/widgets/WootWriter/Editor.vue
> +    isHelpCenter: { type: Boolean, default: false },
Done https://github.com/chatwoot/chatwoot/pull/5961/commits/f7d98e6ce4c9196dd41827f6f38c6f2419230596

2022-12-05 06:08 UTC, fayazara approved these changes
Working as expected tested locally.

https://user-images.githubusercontent.com/15716057/205561530-4a895f16-94c5-4c4f-80c6-5821b18d62dd.mp4

2022-12-06 05:55 UTC, merged