feat: Update Signup screen
chatwoot/chatwoot pull request #6002
Opened 2022-12-01 04:40 UTC by pranavrajs

Fixes https://github.com/chatwoot/marketing/issues/59

<img width="1440" alt="Screenshot 2022-11-30 at 8 37 22 PM" src="https://user-images.githubusercontent.com/2246121/204967133-46764b78-d4fa-4dd0-90ad-32a86114a3bb.png">

2022-12-02 07:13 UTC, nithindavid requested changes

2022-12-02 07:13 UTC, nithindavid commented on app/javascript/dashboard/routes/auth/components/Testimonials/Index.vue
> +      sub-title="You're one step away from engaging your customers, retaining them and finding new ones."
i18n?

2022-12-02 07:13 UTC, nithindavid commented on app/javascript/dashboard/routes/auth/components/Signup/Form.vue
> +  margin-bottom: var(--space-one);
```suggestion
  margin-bottom: var(--space-small);
```

2022-12-02 07:54 UTC, nithindavid commented
<img width="596" alt="image" src="https://user-images.githubusercontent.com/1277421/205243332-03fd4b4d-408b-444c-8f17-329e57a146a8.png">
Should we use the company name instead of the Account name? We could also use a company icon too

2022-12-07 23:42 UTC, pranavrajs commented
1. Made the update to the company name 
<img width="520" alt="Screenshot 2022-12-07 at 3 42 02 PM" src="https://user-images.githubusercontent.com/2246121/206321011-f46bec3d-d6a6-44b5-8788-007e71e80e2c.png">


2. I couldn't get the text working properly. So I have removed it for now.

2022-12-07 23:44 UTC, pranavrajs commented on app/views/installation/onboarding/index.html.erb
> +                  <%= text_field :user, :company, placeholder: "Enter a company name. eg: Wayne Enterprises", required: true %>
```suggestion
                  <%= text_field :user, :company, placeholder: "Enter your company name. eg: Wayne Enterprises", required: true %>
```

2022-12-07 23:55 UTC, merged