feat: feat: Adds number validation for WhatsApp inbox at the creation step
chatwoot/chatwoot pull request #6043
Opened 2022-12-08 09:24 UTC by iamsivin

# Pull Request Template

Fixes https://github.com/chatwoot/product/issues/677

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)

## How Has This Been Tested?
https://www.loom.com/share/ab3dbeaba4484c7d9954ac9f413441fa

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-09 05:00 UTC, pranavrajs approved these changes
Code looks fine. @iamsivin Can you please test it with actual values?

2022-12-09 12:26 UTC, nithindavid requested changes
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/1277421/206702234-04a2b8d3-62e2-436f-a2ec-1975c0bedbc8.png">
The error message for numbers with spaces is misleading, can you add correct the text?

2022-12-09 14:01 UTC, iamsivin commented
> Code looks fine. @iamsivin Can you please test it with actual values?

@pranavrajs Tested it with some dummy values. LGTM.

2022-12-12 06:15 UTC, nithindavid commented on app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
> +          "ERROR": "Please enter a valid value. Phone number should start with a `+` sign and not contain any spaces."
```suggestion
         "ERROR": "Please provide a valid phone number that starts with a `+` sign and does not contain any spaces."
```

2022-12-12 06:17 UTC, nithindavid approved these changes

2022-12-13 03:52 UTC, pranavrajs approved these changes

2022-12-13 03:52 UTC, merged