fix: Unable to save automation "send email to team"
chatwoot/chatwoot pull request #6052
Opened 2022-12-09 11:02 UTC by iamsivin

# Pull Request Template

Fixes https://github.com/chatwoot/chatwoot/issues/6007

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)

## How Has This Been Tested?
https://www.loom.com/share/fd7948c0cbcb4db89d1066f2e4480e06

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-09 12:27 UTC, nithindavid approved these changes

2022-12-09 12:28 UTC, nithindavid commented
@iamsivin Can you please test this on staging and see if emails are getting delivered?

2022-12-09 12:30 UTC, nithindavid requested changes
Please fix codeclimate issue

2022-12-09 17:10 UTC, iamsivin commented
> Please fix codeclimate issue

Done https://github.com/chatwoot/chatwoot/pull/6052/commits/265203916cb1536825ae596481d571d66e0aa9f2

2022-12-09 17:13 UTC, pranavrajs commented on app/javascript/dashboard/helper/actionQueryGenerator.js
> +      if (item.action_params.id) {
@fayazara Please test this this out.

2022-12-12 07:49 UTC, fayazara approved these changes
Tested locally, working correctly now 💯

2022-12-12 14:33 UTC, nithindavid approved these changes

2022-12-12 14:40 UTC, merged