chore: Adds assignee filter in sidebar for home screen
chatwoot/chatwoot pull request #6279
Opened 2023-01-18 11:37 UTC by iamsivin

# Pull Request Template

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
https://www.loom.com/share/e7e6059d8ea2493bb0fb1d93832bb178

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-20 04:21 UTC, nithindavid requested changes

2023-01-20 04:21 UTC, nithindavid commented on app/javascript/dashboard/components/ChatList.vue
> +            @changeSortByFilter="updateSortByFilterType"
@iamsivin Can we change the prop name on filter components to `change` from `changeSortByFilter`? As they are already in the component scope, and there aren't multiple on change events.

2023-01-20 04:21 UTC, nithindavid commented on app/javascript/dashboard/components/ChatList.vue
> +            @changeSortByFilter="updateSortByFilterType"
Please do this for othet components as well

2023-01-20 04:21 UTC, nithindavid commented on app/javascript/dashboard/components/layout/sidebarComponents/SecondaryNavItem.vue
> +      background: var(--s-50);
```suggestion
      background: var(--w-25);
```
Can we try primary color for active items and see if they are good?

2023-03-01 08:34 UTC, sojan-official commented
@nithindavid  @iamsivin  will we be taking this forward ?

2023-03-01 08:37 UTC, iamsivin commented
> @nithindavid  @iamsivin  will we be taking this forward ?

@sojan-official We can close this for now once we found a better way of implementation in UI. 

**ref**: https://github.com/chatwoot/chatwoot/issues/6309

2023-03-01 08:38 UTC, closed without merging