Fixes #6307
chatwoot/chatwoot pull request #6308
Opened 2023-01-20 03:27 UTC by iprithvitharun

- Typo fixed.
- Period added.

2023-01-20 06:23 UTC, nithindavid commented
@Hricha-Shandily Is there a better way to rephrase `Email where your customers send you, support tickets.` ?

2023-01-23 06:34 UTC, Hricha-Shandily requested changes

2023-01-23 06:34 UTC, Hricha-Shandily commented on app/javascript/dashboard/i18n/locale/en/inboxMgmt.json
> +          "SUBTITLE": "Email where your customers send you support tickets.",
```suggestion
          "SUBTITLE": "Provide the email address where your customers send support requests.",
```

2023-01-23 06:40 UTC, nithindavid approved these changes

2023-01-24 06:16 UTC, merged