Rate conversation mailer
chatwoot/chatwoot pull request #7024
Opened 2023-05-03 09:57 UTC by tejaswinichile

[# Pull Request Template

## Description

Please include a summary of the change and issue(s) fixed. Also, mention relevant motivation, context, and any dependencies that this change requires.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
](https://linear.app/chatwoot/issue/CW-1363/rate-the-conversation-is-sent-as-a-message-in-the-emails)

2023-05-03 10:07 UTC, tejaswinichile commented
<img width="443" alt="Screenshot 2023-05-03 at 3 32 04 PM" src="https://user-images.githubusercontent.com/10827585/235888093-8fb705d7-ebc0-4d92-8ec5-33e685910555.png">
<img width="443" alt="Screenshot 2023-05-03 at 3 32 12 PM" src="https://user-images.githubusercontent.com/10827585/235888119-e9b1f6e5-47d9-40e2-abd5-305c8429dadb.png">

I have added the link in new mailer and added the link to rate the conversation.

2023-05-03 11:05 UTC, tejaswinichile commented on app/javascript/dashboard/components/widgets/conversation/Message.vue
> +        const link = `/survey/responses/${this.data.conversation_id}`;
@muhsin-k / @iamsivin Can you help me to add a link here in this message?

2023-05-03 13:01 UTC, tejaswinichile commented
Test Steps:

1. Enable CSAT for inbox.
2. Resolve conversation for inbox.
3. It should include the CSAT survey link in the message so it would include further in the summary email.

2023-05-03 17:10 UTC, pranavrajs commented on app/javascript/dashboard/i18n/locale/en/conversation.json
> +    "CSAT_REPLY_MESSAGE": "Please rate the conversation: %{link}",
@tejaswinichile We shouldn't show this to the agents.

2023-05-03 17:11 UTC, pranavrajs requested changes
Please see my feedback.

2023-05-03 17:11 UTC, pranavrajs commented on app/javascript/dashboard/i18n/locale/en/conversation.json
> +    "CSAT_REPLY_MESSAGE": "Please rate the conversation: %{link}",
This is only required in the emails sent to the customer.

2023-05-04 15:06 UTC, tejaswinichile commented
@pranavrajs Please have a look at this:

<img width="489" alt="Screenshot 2023-05-04 at 5 51 51 PM" src="https://user-images.githubusercontent.com/10827585/236249159-223edeb7-7da2-436b-b6ab-6eb9cea37f83.png">
<img width="489" alt="Screenshot 2023-05-04 at 8 23 21 PM" src="https://user-images.githubusercontent.com/10827585/236249163-784a8dfb-4656-4021-80c1-0c137e3c2e2d.png">

2023-05-10 00:26 UTC, pranavrajs approved these changes

2023-05-10 00:39 UTC, merged