fix: Adds domain option to user cookies set by SDK
chatwoot/chatwoot pull request #7070
Opened 2023-05-12 11:01 UTC by nithindavid

# Pull Request Template

## Description

Please include a summary of the change and issue(s) fixed. Also, mention relevant motivation, context, and any dependencies that this change requires.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-22 13:39 UTC, nithindavid commented
@scmmishra I have done the basic testing with localtunnel and it seems to be working. Can you check the code once? I'll test on some real world scenarios

2023-05-26 06:12 UTC, nithindavid commented
Tested on .chatwoot.com domain here - https://www.loom.com/share/adc53917aa434f23868aceb3a181a734

2023-06-05 07:55 UTC, scmmishra requested changes

2023-06-05 07:55 UTC, scmmishra commented on app/javascript/sdk/cookieHelpers.js
> +  let cookieOptions = {
```suggestion
  const cookieOptions = {
```

2023-06-05 07:55 UTC, scmmishra commented on app/javascript/sdk/cookieHelpers.js
> +export const setCookieWithDomain = (
Let's write tests for this

2023-06-05 07:55 UTC, scmmishra commented
@nithindavid overall the code looks good to go, just a few minor suggestions

2023-06-08 07:00 UTC, nithindavid commented
@scmmishra I have added test cases and added the code suggestion. Please take a look.

2023-06-08 07:02 UTC, scmmishra approved these changes

2023-06-08 08:57 UTC, merged