fix: Translation issues
chatwoot/chatwoot pull request #7416
Opened 2023-06-27 14:09 UTC by iamsivin

# Pull Request Template

Fixes https://linear.app/chatwoot/issue/CW-2108/chore-translation-issues

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-28 10:53 UTC, Hricha-Shandily requested changes

2023-06-28 10:53 UTC, Hricha-Shandily commented on app/javascript/dashboard/i18n/locale/en/cannedMgmt.json
> +        "ERROR_MESSAGE": "Could not update canned response. Please try again later"
```suggestion
        "ERROR_MESSAGE": "Could not update canned response. Please try again later."
```

2023-06-28 10:53 UTC, Hricha-Shandily commented on app/javascript/dashboard/i18n/locale/en/cannedMgmt.json
> +        "ERROR_MESSAGE": "Could not delete canned response. Please try again later"
```suggestion
        "ERROR_MESSAGE": "Could not delete canned response. Please try again later."
```

2023-06-28 10:53 UTC, Hricha-Shandily commented on app/javascript/dashboard/i18n/locale/en/contact.json
> +    "SUCCESS_MESSAGE": "Export is in progress, and you will be notified via email when the export file is ready to download.",
```suggestion
    "SUCCESS_MESSAGE": "Export is in progress. You will be notified on email when the export file is ready to download.",
```

2023-06-28 10:53 UTC, Hricha-Shandily commented on app/javascript/dashboard/i18n/locale/en/cannedMgmt.json
> +        "ERROR_MESSAGE": "Could not create canned response. Please try again later"
```suggestion
        "ERROR_MESSAGE": "Could not create canned response. Please try again later."
```

2023-06-29 09:10 UTC, scmmishra approved these changes

2023-06-29 09:11 UTC, merged