feat: update node to LTS v18
chatwoot/chatwoot pull request #7759
Opened 2023-08-18 05:25 UTC by scmmishra

2023-08-18 10:14 UTC, scmmishra commented
@vn @sojan-official seems like DockerCloud is not working properly, can you folks test this PR to see if I have covered all cases

<img width="621" alt="CleanShot 2023-08-18 at 17 14 15@2x" src="https://github.com/chatwoot/chatwoot/assets/18097732/19653b60-cdea-4d59-8fc6-f49d3a68c308">

2023-08-18 12:02 UTC, vishnu-narayanan commented
@scmmishra 

```
2023-08-18T07:15:32Z #17 [pre-builder 9/14] RUN yarn install
2023-08-18T07:15:32Z #17 0.431 node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
2023-08-18T07:15:32Z #17 ERROR: executor failed running [/bin/sh -c yarn install]: exit code: 9
2023-08-18T07:15:32Z
2023-08-18T07:15:32Z #4 [internal] load metadata for docker.io/library/ruby:3.2.2-alpine3.16
2023-08-18T07:15:32Z ------
2023-08-18T07:15:32Z > [pre-builder 9/14] RUN yarn install:
2023-08-18T07:15:32Z #17 0.431 node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
2023-08-18T07:15:32Z ------
2023-08-18T07:15:32Z ERROR: failed to solve: executor failed running [/bin/sh -c yarn install]: exit code: 9
2023-08-18T07:15:32Z Build failed using Buildkit (1)
```

2023-08-18 19:47 UTC, pranavrajs requested changes
@scmmishra A couple of points here. 

1/ Can't we just go to the latest Node version than 18.17.1?
2/ We need to update the dependencies on [linux installer](https://github.com/chatwoot/chatwoot/blob/develop/deployment/setup_20.04.sh).
3/ How does it work in the development env? Should we just add the NODE_OPTIONS in .bashrc?

2023-08-22 02:00 UTC, scmmishra commented
@pranavrajs sorry missed the comments

> 1/ Can't we just go to the latest Node version than 18.17.1?

Sure, I can try this out.

> 2/ We need to update the dependencies on [linux installer](https://github.com/chatwoot/chatwoot/blob/develop/deployment/setup_20.04.sh).

Noted.

> 3/ How does it work in the development env? Should we just add the NODE_OPTIONS in .bashrc?

Doing this will break a lot of NodeJS CLI apps, for instance, `code`, the way to do it is to export the option inline when running the command.

2023-08-24 08:22 UTC, scmmishra commented on deployment/setup_20.04.sh
> +  curl -sL https://deb.nodesource.com/setup_18.x | bash -
Yeah, I thought so too. However, `nvmrc` is not a node standard, but of a package manager `nvm`. We can however set the value in `package.json` and access it here

```
"engines": {
    "node": "18.x"
}
```

2023-08-24 10:57 UTC, scmmishra commented
Tested the install script on a Ubuntu VM, works fine

<img width="1512" alt="CleanShot 2023-08-24 at 17 56 41@2x" src="https://github.com/chatwoot/chatwoot/assets/18097732/ff912f7b-130c-4349-9191-73d179a21502">

2023-08-25 05:00 UTC, scmmishra commented
> hey Shivam.. can we also incorporate the changes in the PR as well here? https://github.com/chatwoot/chatwoot/pull/7772/files
> 
> so we can test the cwctl in one go

Sure, I'll merge that branch onto this... The changes there are complete right?

2023-08-25 05:03 UTC, sojan-official commented
> https://github.com/chatwoot/chatwoot/pull/7772/files

yep . just need to make sure the node versions match up. also if we are doing the `package.json` parsing for node version

2023-08-25 05:05 UTC, scmmishra commented
> > https://github.com/chatwoot/chatwoot/pull/7772/files
> 
> yep . just need to make sure the node versions match up. also if we are doing the `package.json` parsing for node version

Noted, yeah we can fetch the node version from packagejson using `jq` and use

2023-08-25 05:54 UTC, scmmishra commented
@sojan-official, there is a problem with detecting the node version from `package.json`. The repo cloning setup happens much after the dependencies are installed. So we won't be able to infer the version from there until we modify the script

2023-08-25 09:02 UTC, scmmishra commented
@sojan-official @pranavrajs any idea why Circle CI might be [failing here](https://app.circleci.com/jobs/github/chatwoot/chatwoot/72218) Unable to find the root cause of it, the tests are passing locally

2023-08-28 09:02 UTC, pranavrajs commented
- Updated the docker apk install command to use `nodejs-current` instead of `nodejs` to use 20.5 instead of 18. alpine 3.18 `nodejs-current` points to 20.5 and `nodejs` points to 18.17.
- Added an environment variable NODE_VERSION=20.5.0 in Netlify for the storybook builds to pass.
- Added an environment variable NODE_OPTIONS="--openssl-legacy-provider" on CircleCI.

2023-08-28 13:49 UTC, pranavrajs approved these changes

2023-08-28 13:50 UTC, merged