feat: Adds the ability to see the popular articles
chatwoot/chatwoot pull request #8152
Opened 2023-10-20 07:18 UTC by iamsivin

# Pull Request Template

## Description

This PR adds the popular article section to the main screen.

Fixes https://linear.app/chatwoot/issue/CW-2616/implement-popular-articles-section-in-the-main-page

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

**Screenshot**
![image](https://github.com/chatwoot/chatwoot/assets/64252451/1871959b-820d-489e-b777-20ea2dfa8c1c)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-27 20:17 UTC, nithindavid requested changes
Looks good overall, please see the minor comments.

2023-10-30 04:44 UTC, iamsivin commented on app/views/public/api/v1/portals/_featured_articles.html.erb
> +<% if featured_articles.count >= 6 %>
@nithindavid We will not show the featured articles section if there are less than six articles.

2023-10-30 20:42 UTC, nithindavid commented on app/views/public/api/v1/portals/_featured_articles.html.erb
> +<% if featured_articles.count >= 6 %>
The check is the opposite right?

2023-11-08 14:53 UTC, scmmishra commented on app/views/public/api/v1/portals/_featured_articles.html.erb
> +<% if featured_articles.count >= 6 %>
@nithindavid is right here, we should show whatever is available :)

2023-11-09 02:01 UTC, merged