feat: Updated the design of the category page
chatwoot/chatwoot pull request #8165
Opened 2023-10-23 04:53 UTC by iamsivin

# Pull Request Template

## Description

This PR will update the design of category page

Fixes https://linear.app/chatwoot/issue/CW-2621/update-the-design-of-the-category-page

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

**Screenshot**
![image](https://github.com/chatwoot/chatwoot/assets/64252451/5be0b3cb-9f5d-4027-a36f-8ddc0cabd6a4)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-26 10:06 UTC, muhsin-k approved these changes

2023-10-27 20:49 UTC, nithindavid requested changes
Please see the comments added

2023-10-27 20:49 UTC, nithindavid commented on app/views/public/api/v1/portals/_uncategorized-block.html.erb
> +      href="/hc/<%= portal.slug %>/articles/<%= article.slug %><%= @theme.present? && @theme != 'system' ? '?theme='+@theme : ''  %>"
We could move this to a helper.

2023-10-27 20:49 UTC, nithindavid commented on app/views/public/api/v1/portals/categories/_category-hero.html.erb
> +      <h1 class="text-4xl"><%= category.icon %></h1>
This doesn't need to be in h1 tag. We could use span on merge the two h1's

2023-10-27 20:49 UTC, nithindavid commented on app/views/public/api/v1/portals/categories/_category-hero.html.erb
> +      <h1 class="text-3xl font-semibold leading-snug md:tracking-normal text-slate-900 dark:text-white">
The line height of title and body seems to be different from the figma design.

2023-10-27 20:49 UTC, nithindavid commented on app/views/public/api/v1/portals/categories/_category-hero.html.erb
> +    <%# >By Alexander and 3 others •%>
✍️

2023-10-27 20:49 UTC, nithindavid commented on app/views/public/api/v1/portals/categories/show.html.erb
> +          <%# By Alexander •  %>
✍️

2023-11-08 14:52 UTC, scmmishra commented
@iamsivin approved this, but let's merge the upstream PRs

2023-11-09 02:03 UTC, merged