feat: Enable custom attributes in the suggestion for variables.
chatwoot/chatwoot pull request #8520
Opened 2023-12-09 06:54 UTC by muhsin-k

Fixes https://linear.app/chatwoot/issue/CW-2880/frontend-enable-custom-attributes-in-the-suggestion-for-variables

2023-12-11 06:31 UTC, pranavrajs commented
@muhsin-k @absurdiya We need a new design for this one. The text is not readable. 

**Before:** 
<img alt="Screenshot 2023-12-10 at 10 15 25 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/4a5f2010-637a-41a3-a425-88a2c965a5f4"> 



**Suggestion:** 
![Frame 1 (1)](https://github.com/chatwoot/chatwoot/assets/2246121/9c574e15-b464-4391-8fdb-37e0bd97cb55) |

2023-12-11 06:31 UTC, pranavrajs requested changes
Please see the comment on the design change.

2023-12-11 06:59 UTC, absurdiya commented
> Please see the comment on the design change.
<img width="450" alt="Screenshot 2023-12-11 at 12 28 18 PM" src="https://github.com/chatwoot/chatwoot/assets/69632863/734c63be-9049-40dc-925d-2e4eaa630b17">
Would suggest keeping the hover state like this (bg: blue-2 from Radix (#F5FAFF) and text as primary color), as that is the hover state we are currently using in lists.

2023-12-13 10:26 UTC, scmmishra reviewed
@muhsin-k the code seems fine, lets work on the design suggestions from @pranavrajs and @absurdiya

2023-12-14 14:04 UTC, muhsin-k commented
@pranavrajs I have updated the UI.

**Variables**

<img width="1033" alt="Screenshot 2023-12-14 at 7 32 03 PM" src="https://github.com/chatwoot/chatwoot/assets/12408980/86a04843-a385-40f3-a751-56b6248bcad9">

**Canned responses**

<img width="1019" alt="Screenshot 2023-12-14 at 7 33 09 PM" src="https://github.com/chatwoot/chatwoot/assets/12408980/c4dc081b-fcef-404b-b2ed-a5353d064c89">

2023-12-15 03:57 UTC, scmmishra commented
@pranavrajs @absurdiya please take a look whenever you can

2023-12-19 00:50 UTC, pranavrajs commented
@muhsin-k There is a bug. Please see the screenshot. The value is defined. However, it returns this error.
<img width="1026" alt="Screenshot 2023-12-18 at 4 49 45 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/da59d897-52fa-4581-a625-d2c7a95f488a">

2023-12-19 03:18 UTC, muhsin-k commented
> @muhsin-k There is a bug. Please see the screenshot. The value is defined. However, it returns this error. <img alt="Screenshot 2023-12-18 at 4 49 45 PM" width="1026" src="https://private-user-images.githubusercontent.com/2246121/291443495-da59d897-52fa-4581-a625-d2c7a95f488a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NTU5MzEsIm5iZiI6MTcwMjk1NTYzMSwicGF0aCI6Ii8yMjQ2MTIxLzI5MTQ0MzQ5NS1kYTU5ZDg5Ny01MmZhLTQ1ODEtYTYyNS1kMmM3YTk1ZjQ4OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMDMxMzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzI2OWJlOWIyMWQ2MWU1MjFkY2IxNTJmYzRiMDU2OGJhZWZkZDE2NDRmNzZjMWZkYjZjMWNkMTg5YzU2MTZmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.44JHQ4VktBoJ_JYT5xl5rJH04gmDqZFzY7tiue_rAfo">

@pranavrajs Did you run 'yarn install' after pulling the branch? The logic for this operation exists in the utils library.

2023-12-20 04:40 UTC, iamsivin commented on yarn.lock
> +"@chatwoot/utils@0.0.18":
@muhsin-k Do we need this version change? In pakage.json, the version is `0.0.16`.

2023-12-20 05:45 UTC, iamsivin approved these changes
@muhsin-k I have tested this PR locally with canned responses and variables, and it appears to be functioning properly. I have attached a Loom video below for reference.

I also have some suggestions. Please feel free to ignore them if they are not relevant.
1. When the checkbox attribute is added and its value is set to false, attempting to send a message triggers an undefined modal. Clicking 'Yes' in this modal sends a message with the value 'false'. Do we need to display the modal in this scenario?

2. Regarding the date custom attributes: the date displayed in the sidebar is formatted as '20/12/2023', but when sent, it appears in the message bubble in the format '2023-12-19T18:30:00.000Z'. Should we standardize the date format for consistency?
https://www.loom.com/share/784d0f4920db467c80e88679401ca6bf?sid=4446da15-0ce2-4f33-a2d8-0100c8974b9f

2023-12-20 05:49 UTC, iamsivin commented on yarn.lock
> +"@chatwoot/utils@0.0.18":
```suggestion
"@chatwoot/utils@^0.0.18":
```

2023-12-20 06:13 UTC, muhsin-k commented
>
> 1. When the checkbox attribute is added and its value is set to false, attempting to send a message triggers an undefined modal. Clicking 'Yes' in this modal sends a message with the value 'false'. Do we need to display the modal in this scenario?

I have added fix for this issue.

> 2. Regarding the date custom attributes: the date displayed in the sidebar is formatted as '20/12/2023', but when sent, it appears in the message bubble in the format '2023-12-19T18:30:00.000Z'. Should we standardize the date format for consistency?

I will handle this as a follow-up ticket.

2023-12-20 06:50 UTC, merged