docs: Add filter status=all to conversation list and meta
chatwoot/chatwoot pull request #8994
Opened 2024-02-22 13:54 UTC by danilofuchs

# Pull Request Template

## Description

The code skips filtering if status=all in the query params, but the documentation was out of date:

https://github.com/SalvyLTD/chatwoot/blob/3fec1e195e3c4f5e3d41e6180f0b96d07de40e72/app/finders/conversation_finder.rb#L130

Closes #8993

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-22 23:26 UTC, pranavrajs requested changes
Please see the comment above.

2024-02-26 20:48 UTC, danilofuchs commented
@pranavrajs 
I believe this is now corrected

2024-02-26 23:15 UTC, pranavrajs approved these changes

2024-02-26 23:15 UTC, pranavrajs commented
Great, thanks! Merging it now.

2024-02-26 23:15 UTC, merged