feat: SLA report filter
chatwoot/chatwoot pull request #9218
Opened 2024-04-10 07:26 UTC by iamsivin

# Pull Request Template

## Description

This PR includes filtering SLA reports by agents, Inboxes, SLA policies, teams, and labels.

Fixes https://linear.app/chatwoot/issue/CW-3190/use-the-filter-components-in-the-reports

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

**Loom video**
https://www.loom.com/share/abb07e83bf7e4ac89abeb22802a0aff7?sid=22e7e36f-3a11-4582-b0be-3d22a63e0edf

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-10 14:53 UTC, scmmishra requested changes
@iamsivin I moved the active filters as a separate component in `ActiveFilterChip.vue` tried to reduce the amount of template we have. See if you can do it for that for the main `Add filter` button too. Once done, it'll be easier to see how we can split the logic also

2024-04-11 11:27 UTC, scmmishra approved these changes

2024-04-11 11:28 UTC, scmmishra commented
@iamsivin the changes look good for now. We can revaluate the filter components and see if the components can be simplified once we reuse it elsewhere

2024-04-12 03:26 UTC, muhsin-k commented
@iamsivin Should we display the "Add Filter" button if all filters are selected? In my opinion, only the "Clear All" button is necessary in that case.
![CleanShot 2024-04-12 at 08 38 47@2x](https://github.com/chatwoot/chatwoot/assets/12408980/6775cd78-6f6a-48f6-82d7-77bf5a43436f)

2024-04-12 03:27 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/reports/components/SLA/SLAFilter.vue
> +    hasActiveFilters() {
We can simplify it by directly checking if any of the `appliedFilters` has a value other than null. This approach eliminates the need to first compute `activeFilters` just to check if any filters are active.

```
hasActiveFilters() {
   return Object.values(this.appliedFilters).some(value => value !== null);
},
```

2024-04-12 05:13 UTC, muhsin-k approved these changes
LGTM

2024-04-12 05:33 UTC, merged