chore: Replace eventBus with mitt.js [CW-3275]
chatwoot/chatwoot pull request #9539
Opened 2024-05-24 11:24 UTC by fayazara

# Replace the deprecated `eventBus` with mitt.js

## Description

Since eventBus and it's respective methods are deprecated and removed from all future releases of vue, this was blocking us from migrating. This PR replaces eventBus with [mitt](https://github.com/developit/mitt). I have created a wrapper mitt.js to simulate the same old event names so it's backwards compatible, without making a lot of changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

1. Made sure all the places we're listening to bus events are working as expected.
2. Respective specsf or the events from mitt.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-05-28 04:17 UTC, fayazara commented
Note for self : Get more info on -
`app/javascript/dashboard/components/ui/DatePicker/DatePicker.vue` - Vue 3 script syntax

`app/javascript/v3/components/SnackBar/Container.vue`

2024-05-28 06:39 UTC, scmmishra requested changes
One tiny change, the rest is good to go.

2024-05-28 06:39 UTC, scmmishra commented on app/javascript/dashboard/components/ui/DatePicker/DatePicker.vue
Let's replace these also with `showAlert`

2024-05-28 10:47 UTC, scmmishra approved these changes

2024-05-30 04:58 UTC, scmmishra requested changes
@fayazara there are instances where we have potential infintie loops, where `showAlert` is already a function defined in the component, and then the mixin is added which calls `showAlert` again. PTAL

![CleanShot 2024-05-30 at 10 26 50@2x](https://github.com/chatwoot/chatwoot/assets/18097732/07c015cf-7ff4-4885-990b-8522ddf6ebe9)

2024-05-30 19:04 UTC, fayazara commented
@scmmishra this was a really good catch. Some of these methods were doing more than just showing alerts, hence renamed them to showAlertMessage.

![CleanShot 2024-05-31 at 00 32 36@2x](https://github.com/chatwoot/chatwoot/assets/15716057/37642b47-a432-437d-870f-471dd282f37e)

2024-05-31 07:49 UTC, scmmishra approved these changes

2024-05-31 10:19 UTC, muhsin-k approved these changes

2024-05-31 10:20 UTC, merged