feat: Add issue status in linear issue search item
chatwoot/chatwoot pull request #9598
Opened 2024-06-05 10:42 UTC by muhsin-k

![CleanShot_2024-06-05_at_16 08 202x](https://github.com/chatwoot/chatwoot/assets/12408980/ae92655d-9c10-4c67-809f-0db782d6b82f)

2024-06-07 11:05 UTC, scmmishra requested changes

2024-06-07 11:05 UTC, scmmishra commented on app/javascript/dashboard/components/ui/Dropdown/DropdownListItemButton.vue
> +  leftIcon: {
Do we need to call it `leftIcon`, we can just call it `icon`, same with `leftIconColor`

2024-06-07 11:05 UTC, scmmishra commented on app/javascript/dashboard/components/ui/Dropdown/DropdownListItemButton.vue
> +        icon="status"
```suggestion
        icon="status"
```

Is this okay to be hardcoded?

2024-08-08 07:34 UTC, muhsin-k commented
@scmmishra Resolved all the comments. Could you please take a look?

2024-08-08 07:43 UTC, scmmishra approved these changes

2024-08-08 08:14 UTC, merged