feat: add automation rule event conversation resolved
chatwoot/chatwoot pull request #9669
Opened 2024-06-23 00:30 UTC by clairton

# Description

add automation rule event conversation resolved

<img width="1552" alt="Captura de Tela 2024-06-22 às 21 25 39" src="https://github.com/chatwoot/chatwoot/assets/471685/b3a64ebc-35c8-468c-a0e5-7974134a40f9">

2024-07-03 22:16 UTC, sojan-official commented
@clairton  Thanks for the changes. Could you also look into adding some specs for the new event, or is it something you would need help with?

2024-08-03 12:17 UTC, clairton commented
@sojan-official I do some days ago

2024-08-05 03:29 UTC, vitor-help commented
Thank you, bro, this solution is awesome.

2024-09-10 04:05 UTC, rudcode commented
+1

2025-06-17 08:02 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
> +      { key: 'assign_agent', name: 'ASSIGN_AGENT' },
Remove the duplicate assign_agent action

2025-06-17 08:05 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
> +      { key: 'send_email_transcript', name: 'SEND_EMAIL_TRANSCRIPT' },
The action list includes actions that don't make sense after resolution:
  - mute_conversation - pointless on resolved conversations
  - snooze_conversation - can't snooze resolved conversations
  - assign_agent - typically unnecessary post-resolution

2025-06-17 08:11 UTC, muhsin-k requested changes
I have tested this PR and the feature is not functioning properly. [https://www.loom.com/share/7166f610775d4f4bbd33562ad3b8ce14](https://github.com/7166f610775d4f4bbd33562ad3b8ce14)

2025-06-17 08:11 UTC, muhsin-k commented on app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
> +      { key: 'send_email_transcript', name: 'SEND_EMAIL_TRANSCRIPT' },
@sojan-official @scmmishra Thoughts?

2025-06-18 16:40 UTC, clairton commented on app/javascript/dashboard/routes/dashboard/settings/automation/constants.js
> +      { key: 'send_email_transcript', name: 'SEND_EMAIL_TRANSCRIPT' },
I use assign_agent to assign to none agent in automation when resolve conversation

2025-07-04 06:17 UTC, muhsin-k commented
@clairton Thanks for raising this PR! I’ve added some comments, could you please take a look? Also, let me know if you’d prefer me to make the suggested changes, or if you’d like to update them yourself.

2025-07-10 15:04 UTC, lucianodltec commented
+1

2025-07-28 10:47 UTC, muhsin-k approved these changes

2025-08-13 07:27 UTC, merged