feat: Rewrite `agentMixin` to a helper
chatwoot/chatwoot pull request #9940
Opened 2024-08-12 14:47 UTC by iamsivin

# Pull Request Template

## Description

This PR will replace the usage of `agentMixin`with the utility helpers functions.

**Files updated**

1. dashboard/components/widgets/conversation/contextMenu/Index.vue
2. dashboard/components/widgets/conversation/ConversationHeader.vue **(Not used)**
3. dashboard/routes/dashboard/commands/commandbar.vue
4. dashboard/routes/dashboard/conversation/ConversationAction.vue
5. dashboard/routes/dashboard/conversation/ConversationParticipant.vue

Fixes https://linear.app/chatwoot/issue/CW-3442/rewrite-agentmixin-mixin-to-a-composable

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

**Test cases**

1. See agent list sorting based on availability, if agents are on the same status, then sorted by name.
2. Test actions like assigning/unassigning agent from conversation sidebar, CMD bar, Context menu.
3. Test actions like adding/removing participants from conversation sidebar.
4. See agent list is generated properly, none value.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-08-12 14:50 UTC, iamsivin commented on app/javascript/dashboard/helper/agentHelper.js
@scmmishra I have moved the usage of `agentMixin` to `agentHelper.js` instead of composable. WDYT?

2024-08-13 03:59 UTC, scmmishra commented on app/javascript/dashboard/helper/agentHelper.js
Sounds good!

2024-08-13 04:01 UTC, scmmishra commented on app/javascript/dashboard/helper/agentHelper.js
@iamsivin it seems that there is a lot of setup required to get the data from `generateAgentsList` it would be better to be a composable since the logic is being replicated in multiple places at the moment, and I can see this being re-used in the future

2024-08-13 04:02 UTC, scmmishra requested changes
@iamsivin let's use a composable

2024-08-13 06:32 UTC, iamsivin commented on app/javascript/dashboard/helper/agentHelper.js
@scmmishra Updated the PR with the suggestions. Moved the `generateAgentsList ` to the `useAgentsList` composable as `agentsList` and used in the components.

2024-08-21 12:28 UTC, scmmishra approved these changes

2024-08-21 12:50 UTC, scmmishra commented on app/javascript/dashboard/composables/useAgentsList.js
If we use `useMapGetter` can we simplify this? Also get rid of the codeclimate issue

```
export function useAgentsList(includeNoneAgent = true) {
  const currentUser = useMapGetter('getCurrentUser');
  const currentChat = useMapGetter('getSelectedChat');
  const currentAccountId = useMapGetter('getCurrentAccountId');
  const assignable = useMapGetter('inboxAssignableAgents/getAssignableAgents');

  const inboxId = computed(() => currentChat.value?.inbox_id);
  const isAgentSelected = computed(() => currentChat.value?.meta?.assignee);

  /**
   * @type {import('vue').ComputedRef<Array>}
   */
  const assignableAgents = computed(() => {
    return inboxId.value ? assignable.value(inboxId.value) : [];
  });

  /**
   * @type {import('vue').ComputedRef<Array>}
   */
  const agentsList = computed(() => {
    const agents = assignableAgents.value || [];
    const agentsByUpdatedPresence = getAgentsByUpdatedPresence(
      agents,
      currentUser.value,
      currentAccountId.value
    );

    const filteredAgentsByAvailability = getSortedAgentsByAvailability(
      agentsByUpdatedPresence
    );

    const filteredAgents = [
      ...(includeNoneAgent && isAgentSelected.value ? [createNoneAgent] : []),
      ...filteredAgentsByAvailability,
    ];
    return filteredAgents;
  });

  return {
    agentsList,
    assignableAgents,
  };
}
```

2024-08-22 07:26 UTC, iamsivin reviewed
@scmmishra Could you please take a round of look? If it's good, I will merge it.

2024-08-22 07:31 UTC, scmmishra approved these changes

2024-08-22 07:32 UTC, merged